### ISSUE TITLE
Does not appear to block Twitter Blue users in comments consistently.

### ISSUE THREAD

**Issue by LeviSnoot** [kheina-com/Blue-Blocker#1]
I scrolled through the comments on a Musk tweet to test the extension with the console open and the success rate was around 20%. It appears that the block event is more consistent by visiting the users profile and then opening a tweet or sometimes two.

The log message for blocks is also always `blocked USER (@USER) due to NFT avatar.` regardless if they actually do have an NFT avatar or not.

**Comment by Speedy2662** [comment]
+1, please fix

**Comment by HEYimHeroic** [comment]
yeah having the same issue it seems :/

**Comment by kalmasri123** [comment]
I made a fork to fix it. I'll PR soon

**Comment by DeScruff** [comment]
Well be careful with this now. Cause it seems like some are having blue forced on them.

**Comment by Speedy2662** [comment]
> Well be careful with this now. Cause it seems like some are having blue forced on them.

What, Stephen King and Lebron James? lol i'll take my chances

**Comment by Speedy2662** [comment]
> Well be careful with this now. Cause it seems like some are having blue forced on them.

Likely just saying they didn't buy it to avoid backlash lol

**Comment by DeScruff** [comment]
> Likely just saying they didn't buy it to avoid backlash lol

... No seriously. Unless you want to say literal dead people with inactive accounts have risen from the grave just to pay for twitter. (It seems like anyone over 1 million followers instantly gets Blue now.)
Then you have Elon critics like Matt Binder, dril, Owen Jones. exc exc.

**Comment by Speedy2662** [comment]
> > Likely just saying they didn't buy it to avoid backlash lol
> 
> ... No seriously. Unless you want to say literal dead people with inactive accounts have risen from the grave just to pay for twitter. (It seems like anyone over 1 million followers instantly gets Blue now.) Then you have Elon critics like Matt Binder, dril, Owen Jones. exc exc.

Dang, you're right lol. Elmo is giving ticks to everyone with over 1M followers and claiming 'they are subscribed to Blue'. Absolutely pathetic

**Comment by babegeman** [comment]
> I made a fork to fix it. I'll PR soon

Hey yours works great but there is an issue, if you visit the most infested threads you'll get logged out because of the mass number of blocks. I wonder if it would be worthwhile to instead of instantly blocking to create a queue that would block them on a cadence that wouldn't trigger the auto-logout of Twitter. Worth considering.

Another stretch feature that would be awesome would be some metrics. Like a queue size that you could see slowly tick over to the blocked number.

**Comment by kalmasri123** [comment]
> > I made a fork to fix it. I'll PR soon
> 
> Hey yours works great but there is an issue, if you visit the most infested threads you'll get logged out because of the mass number of blocks. I wonder if it would be worthwhile to instead of instantly blocking to create a queue that would block them on a cadence that wouldn't trigger the auto-logout of Twitter. Worth considering.
> 
> Another stretch feature that would be awesome would be some metrics. Like a queue size that you could see slowly tick over to the blocked number.



Good idea! I'll look into this

**Comment by DanielleMiu** [comment]
may have been fixed as a part of https://github.com/kheina-com/Blue-Blocker/pull/10
