### ISSUE TITLE
Unable to block suspended users - Causes Blue Blocker to stop working

### ISSUE THREAD

**Issue by Butternubs** [kheina-com/Blue-Blocker#101]
Whenever I get the chance, I'll scroll down search and add as many users as I can to my block list, however it appears as though if a user gets suspended before Blue Blocker can actually block them, Blue Blocker just gets stuck in a loop, as the API just returns an error.

![image](https://github.com/kheina-com/Blue-Blocker/assets/9280620/94587b3b-b693-4985-b1c7-38e990e3e9db)

Having access to a raw block list in some capacity would be amazing, so we could solve this sort of stuff manually rather than hoping for a fix in the near future.

TIA!

**Comment by DanielleMiu** [comment]
working on it

**Comment by DanielleMiu** [comment]
by the way, is that an adventure time reference

**Comment by Butternubs** [comment]
> by the way, is that an adventure time reference

It sure is! Jake’s pseudonym at the ball in one of the earlier episodes ha.

**Comment by DanielleMiu** [comment]
how could I forget randy butternubs

**Comment by DanielleMiu** [comment]
fixed by https://github.com/kheina-com/Blue-Blocker/pull/99
