### ISSUE TITLE
TweetDeck compatibility

### ISSUE THREAD

**Issue by millionsofplayers** [kheina-com/Blue-Blocker#103]
I'm not sure if there's no tweetdeck compatibility or if i just didn't wait long enough but that's basically the only thing stopping me from switching to tweetdeck + btd

**Comment by DanielleMiu** [comment]
closed in favor of https://github.com/kheina-com/Blue-Blocker/issues/72 and https://github.com/kheina-com/Blue-Blocker/issues/98

also, it's probably mostly compatible already. I'll see what I can do
