### ISSUE TITLE
Add a little more padding to the options modal

### ISSUE THREAD

**Issue by konomikitten** [kheina-com/Blue-Blocker#106]
Currently the modal window gets some of the text chopped off for me, it'd be nice if the padding could be increased slightly to fix this.

![BlueBlocker cut off text issue](https://github.com/kheina-com/Blue-Blocker/assets/12713710/10917430-c6c8-4991-beac-5cf7ab23eb97)

**Comment by DanielleMiu** [comment]
what browser are you using?

**Comment by konomikitten** [comment]
`Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0` For reference this is on XFCE, so it's probably something to do with GTK.

**Comment by DanielleMiu** [comment]
hm. I'm running the latest version of firefox so it's not 1:1, but I don't have this issue at all, I'm assuming firefox changed how it handles context menu overflow. if you untick popups and the 1m followers option does it resolve both scrollbars?

**Comment by konomikitten** [comment]
Afraid not, stays the same.

**Comment by konomikitten** [comment]
I also noticed there's a small erroneous line in the bottom corner as well.

![BlueBlocker erroneous line](https://github.com/kheina-com/Blue-Blocker/assets/12713710/84a6504e-cf88-467d-bbf8-5da2111fc059)

**Comment by konomikitten** [comment]
I moved the add-on icon out of the overflow menu and now it displays just fine, can anyone check if it's an issue in newer Firefox versions in the overflow menu, I believe they updated it a bit so it might be the only the old version that has this issue.

**Comment by DanielleMiu** [comment]
not an issue in 112 on linux. I'm also 99% sure that all of this will be fixed with the change to manifest v3 as well, when we're able to do that. I already know that v2 uses weird css rules and rendering and that's the cause of all the styling problems in firefox

**Comment by konomikitten** [comment]
Okay, that's not far off for ESR closing this bug.

**Comment by DanielleMiu** [comment]
yeah, we can revisit in september or whatever when we migrate to v3. also good job blocking 5,480 blue users

**Comment by konomikitten** [comment]
I'm proud of that number, every day I browse a post from a certain person and add a few more.
