### ISSUE TITLE
Streaming console errors

### ISSUE THREAD

**Issue by mkarman** [kheina-com/Blue-Blocker#109]
Errors in connection / handshake / body response parsing today, unsure if indicative of a change on Twitter's side or network errors.

**Comment by DanielleMiu** [comment]
can you let me know exactly which pages you were on when you were seeing these issues?

**Comment by alanpaone** [comment]
I'm not sure if this is the same error, but I got an error popup mixed in with the block notifications that said to check the console and open an issue on github, this is what was in my console.
>[Blue Blocker] exepected error occurred while parsing request body: 
>Object
>body_str: [BlueBlocker Console Error issue 109.txt](https://github.com/kheina-com/Blue-Blocker/files/11569666/BlueBlocker.Console.Error.issue.109.txt)
>(anonymous) @ chrome-extension://j…mhpmm/shared.js:150

**Comment by DanielleMiu** [comment]
I'll look more into it. thanks for the console output, that helps a lot. I don't think this is a major issue, but something weird in this particular response body. let me know if you encounter any other errors

**Comment by mkarman** [comment]
Sorry for the delay! Was exporting this as I got dragged away for things.

[Blue Blocker] exepected error occurred while parsing request body: {body_str: '{"data":{"threaded_conversation_with_injections
[twitter.com-1685023375064.log](https://github.com/kheina-com/Blue-Blocker/files/11574414/twitter.com-1685023375064.log)
_v2…ode_config":{"is_reader_mode_available":true}}}}}

**Comment by DanielleMiu** [comment]
hey @mkarman, I'm deleting your comment here because it has your authorization header in it. when you post here make sure you're only posting the error log, and not the full console output

**Comment by rougetimelord** [comment]
Closing as stale
