### ISSUE TITLE
Add an elective mode to cull everyone on screen?

### ISSUE THREAD

**Issue by muuyo** [kheina-com/Blue-Blocker#111]
I'd much rather choose to "cull" everyone on the page I'm currently viewing - somewhat manually - than have it passively, where good stuff might fall through the cracks. A button in the UI that adds every blue user on screen to the queue (so I can constantly leave it paused) would be nice, instead of having to disable and enable it.

**Comment by muuyo** [comment]
also, a toggle for the actual blue blocking functionality independent of the NFT avatars would be nice - I find people with NFT avatars are almost universally annoying, but people with Blue might be artists I like or something.

**Comment by thetoastcaper** [comment]
+1 for this. I'd rather have some kind of nuke button to block every blue subscriber in a thread or whatever, the passive mode just feels too out of my control.

**Comment by DanielleMiu** [comment]
so, this extension works by intercepting the requests made by the browser to retrieve users and tweets on twitter, and not by parsing the html (the actual page you see on screen) so this would be pretty difficult to implement. I'm not saying it won't happen, just that that's not how the extension works currently. twitter's html is also infamously terrible so this might be a bigger ask than it seems at first glance.

additionally, there are other extensions that interact with the html, either by adding or changing verified checkmarks like [Twitter Real Verified](https://addons.mozilla.org/en-US/firefox/addon/twitter-real-verified) that might have unintended consequences.
