### ISSUE TITLE
Clicking on removed tweet causes Blue Blocker error

### ISSUE THREAD

**Issue by rwestman** [kheina-com/Blue-Blocker#112]
Sometimes tweets deleted after being posted still appear in the UI, presumably because they were fetched by the client before being deleted.  They appear just like a normal tweet, but when you click on them, you get an error from Twitter.  But you also get an error message from Blue Blocker, saying it should be reported here ("an error occurred! check the console and create an issue on GitHub").  Perhaps this is an error that could be detected and accepted silently?  

The associated console message is as follows:

`shared.js:150 [Blue Blocker] exepected error occurred while parsing request body: Objectbody_str: "{\"errors\":[{\"message\":\"_Missing: No status found with that ID.\",\"locations\":[{\"line\":5,\"column\":3}],\"path\":[\"threaded_conversation_with_injections_v2\"],\"extensions\":{\"name\":\"GenericError\",\"source\":\"Server\",\"code\":144,\"kind\":\"NonFatal\",\"tracing\":{\"trace_id\":\"24224ed51de76260\"}},\"code\":144,\"kind\":\"NonFatal\",\"name\":\"GenericError\",\"source\":\"Server\",\"tracing\":{\"trace_id\":\"24224ed51de76260\"}}],\"data\":{}}"error: {}[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()event: {}[[Prototype]]: Object
(anonymous) @ shared.js:150
`

**Comment by rougetimelord** [comment]
I'm pretty sure that the code now checks if there are errors returned by the API even if the response has a 200 status. Should be fixed already.
