### ISSUE TITLE
Error Notice While Typing in Twitter Handles

### ISSUE THREAD

**Issue by shaunduke** [kheina-com/Blue-Blocker#113]
Apologies if this is already listed. I didn't see it when I searched.

I've started getting a repeat error message when I type in any Twitter handle and the automatic search list comes up on Twitter. If I keep that account search window open, the error repeats and repeats and piles up, and I cannot X the errors out despite there being an X there for that purpose. It only appears to happen when I perform this action on Twitter. 

I don't know if pulling the errors from the console would be helpful, but if so, let me know and I'll C+P them here.

Thanks to anyone who looks into this.

**Comment by DanielleMiu** [comment]
adding the errors from the console here would be extremely helpful, since I can't replicate it easily. make sure you don't copy any of the "headers copied" debug messages, as those will contain your login credentials for twitter

**Comment by shaunduke** [comment]
Hi Danielle,

So, this is what I pulled from the console when I recreated the error just now (started typing a handle, the box of suggested handles came up, and then the error). I saved this as a txt direct from the console section in devtools and then C+Ped that text here. I imagine most of this is just info about the accounts that showed up while I typed the handle in question (@skiffyandfanty was the intended handle), but I didn't know what information should be dumped, so I included it all here. 

shared.js:150 [Blue Blocker] exepected error occurred while parsing request body: {body_str: '{"num_results":10,"users":[{"id":141991393,"id_str…"hashtags":[],"completed_in":0.0,"query":"skiff"}', error: {…}, event: {…}}body_str: "{\"num_results\":10,\"users\":[{\"id\":141991393,\"id_str\":\"141991393\",\"verified\":false,\"ext_is_blue_verified\":false,\"is_dm_able\":true,\"is_secret_dm_able\":false,\"is_blocked\":false,\"can_media_tag\":true,\"name\":\"Skiffy and Fanty \\ud83c\\udf99\",\"screen_name\":\"SkiffyandFanty\",\"profile_image_url\":\"http:\\/\\/pbs.twimg.com\\/profile_images\\/952622901307457536\\/MwPzrbSz_normal.jpg\",\"profile_image_url_https\":\"https:\\/\\/pbs.twimg.com\\/profile_images\\/952622901307457536\\/MwPzrbSz_normal.jpg\",\"location\":\"Abandoned Satellite Over Fiji\",\"is_protected\":false,\"rounded_score\":0,\"social_proof\":0,\"connecting_user_count\":0,\"connecting_user_ids\":[],\"social_proofs_ordered\":[],\"social_context\":{\"following\":true,\"followed_by\":true},\"tokens\":[],\"inline\":false,\"result_context\":{\"display_string\":\"You follow each other\",\"types\":[{\"type\":\"follow_relationship\"}]}},{\"id\":967965224392257536,\"id_str\":\"967965224392257536\",\"verified\":false,\"ext_is_blue_verified\":false,\"is_dm_able\":true,\"is_secret_dm_able\":false,\"is_blocked\":false,\"can_media_tag\":true,\"name\":\"Skiffily Podcast\",\"screen_name\":\"SkiffilyPodcast\",\"profile_image_url\":\"http:\\/\\/pbs.twimg.com\\/profile_images\\/1041191991558561792\\/jQ0kD0p2_normal.jpg\",\"profile_image_url_https\":\"https:\\/\\/pbs.twimg.com\\/profile_images\\/1041191991558561792\\/jQ0kD0p2_normal.jpg\",\"location\":\"Arizona, USA\",\"is_protected\":false,\"rounded_score\":0,\"social_proof\":0,\"connecting_user_count\":0,\"connecting_user_ids\":[],\"social_proofs_ordered\":[],\"social_context\":{\"following\":true,\"followed_by\":true},\"tokens\":[],\"inline\":false,\"result_context\":{\"display_string\":\"You follow each other\",\"types\":[{\"type\":\"follow_relationship\"}]}},{\"id\":1349093539007901696,\"id_str\":\"1349093539007901696\",\"verified\":false,\"ext_is_blue_verified\":true,\"is_dm_able\":true,\"is_secret_dm_able\":false,\"is_blocked\":false,\"can_media_tag\":true,\"name\":\"Skiff\",\"screen_name\":\"skiffprivacy\",\"profile_image_url\":\"http:\\/\\/pbs.twimg.com\\/profile_images\\/1526732663343656960\\/u-lpm_mY_normal.jpg\",\"profile_image_url_https\":\"https:\\/\\/pbs.twimg.com\\/profile_images\\/1526732663343656960\\/u-lpm_mY_normal.jpg\",\"location\":\"Try Skiff for free  \\u2192\",\"is_protected\":false,\"rounded_score\":0,\"social_proof\":0,\"connecting_user_count\":0,\"connecting_user_ids\":[],\"social_proofs_ordered\":[],\"tokens\":[],\"inline\":false},{\"id\":24640770,\"id_str\":\"24640770\",\"verified\":false,\"ext_is_blue_verified\":true,\"is_dm_able\":false,\"is_secret_dm_able\":false,\"is_blocked\":false,\"can_media_tag\":true,\"name\":\"Mike Skiff\",\"screen_name\":\"mikeskiff\",\"profile_image_url\":\"http:\\/\\/pbs.twimg.com\\/profile_images\\/1347305146754031661\\/3zCcmKmQ_normal.jpg\",\"profile_image_url_https\":\"https:\\/\\/pbs.twimg.com\\/profile_images\\/1347305146754031661\\/3zCcmKmQ_normal.jpg\",\"location\":\"Tacoma, WA\",\"is_protected\":false,\"rounded_score\":0,\"social_proof\":0,\"connecting_user_count\":0,\"connecting_user_ids\":[],\"social_proofs_ordered\":[],\"tokens\":[],\"inline\":false},{\"id\":7465732,\"id_str\":\"7465732\",\"verified\":false,\"ext_is_blue_verified\":false,\"is_dm_able\":true,\"is_secret_dm_able\":false,\"is_blocked\":false,\"can_media_tag\":true,\"name\":\"Dillon Skiffington\",\"screen_name\":\"Skiffington_\",\"profile_image_url\":\"http:\\/\\/pbs.twimg.com\\/profile_images\\/1587891560267493376\\/R8uiDlx__normal.jpg\",\"profile_image_url_https\":\"https:\\/\\/pbs.twimg.com\\/profile_images\\/1587891560267493376\\/R8uiDlx__normal.jpg\",\"location\":\"Los Angeles, CA\",\"is_protected\":false,\"rounded_score\":0,\"social_proof\":0,\"connecting_user_count\":0,\"connecting_user_ids\":[],\"social_proofs_ordered\":[],\"tokens\":[],\"inline\":false},{\"id\":256132061,\"id_str\":\"256132061\",\"verified\":false,\"ext_is_blue_verified\":true,\"is_dm_able\":false,\"is_secret_dm_able\":false,\"is_blocked\":false,\"can_media_tag\":false,\"name\":\"Skiffy McGee\",\"screen_name\":\"skiffymcgee\",\"profile_image_url\":\"http:\\/\\/pbs.twimg.com\\/profile_images\\/1446513364671373324\\/eO3BAgRk_normal.jpg\",\"profile_image_url_https\":\"https:\\/\\/pbs.twimg.com\\/profile_images\\/1446513364671373324\\/eO3BAgRk_normal.jpg\",\"location\":\"\",\"is_protected\":false,\"rounded_score\":0,\"social_proof\":0,\"connecting_user_count\":0,\"connecting_user_ids\":[],\"social_proofs_ordered\":[],\"tokens\":[],\"inline\":false},{\"id\":56101539,\"id_str\":\"56101539\",\"verified\":false,\"ext_is_blue_verified\":false,\"is_dm_able\":true,\"is_secret_dm_able\":false,\"is_blocked\":false,\"can_media_tag\":true,\"name\":\"Skiff Life\",\"screen_name\":\"skiff_life\",\"profile_image_url\":\"http:\\/\\/pbs.twimg.com\\/profile_images\\/469797860418928640\\/ozMFAXdd_normal.png\",\"profile_image_url_https\":\"https:\\/\\/pbs.twimg.com\\/profile_images\\/469797860418928640\\/ozMFAXdd_normal.png\",\"location\":\"Skinny Water, U.S.A\",\"is_protected\":false,\"rounded_score\":0,\"social_proof\":0,\"connecting_user_count\":0,\"connecting_user_ids\":[],\"social_proofs_ordered\":[],\"tokens\":[],\"inline\":false},{\"id\":16746621,\"id_str\":\"16746621\",\"verified\":false,\"ext_is_blue_verified\":false,\"is_dm_able\":true,\"is_secret_dm_able\":false,\"is_blocked\":false,\"can_media_tag\":true,\"name\":\"The Skiff\",\"screen_name\":\"theskiff\",\"profile_image_url\":\"http:\\/\\/pbs.twimg.com\\/profile_images\\/1529028028\\/theskiff_logo_2011_normal.png\",\"profile_image_url_https\":\"https:\\/\\/pbs.twimg.com\\/profile_images\\/1529028028\\/theskiff_logo_2011_normal.png\",\"location\":\"Brighton, UK\",\"is_protected\":false,\"rounded_score\":0,\"social_proof\":0,\"connecting_user_count\":0,\"connecting_user_ids\":[],\"social_proofs_ordered\":[],\"tokens\":[],\"inline\":false},{\"id\":20700719,\"id_str\":\"20700719\",\"verified\":false,\"ext_is_blue_verified\":false,\"is_dm_able\":true,\"is_secret_dm_able\":false,\"is_blocked\":false,\"can_media_tag\":false,\"name\":\"Jennifer Skiff\",\"screen_name\":\"JenniferSkiff\",\"profile_image_url\":\"http:\\/\\/pbs.twimg.com\\/profile_images\\/915145128741814272\\/8229TkwT_normal.jpg\",\"profile_image_url_https\":\"https:\\/\\/pbs.twimg.com\\/profile_images\\/915145128741814272\\/8229TkwT_normal.jpg\",\"location\":\"USA & Australia\",\"is_protected\":false,\"rounded_score\":0,\"social_proof\":0,\"connecting_user_count\":0,\"connecting_user_ids\":[],\"social_proofs_ordered\":[],\"tokens\":[],\"inline\":false},{\"id\":9582172,\"id_str\":\"9582172\",\"verified\":false,\"ext_is_blue_verified\":false,\"is_dm_able\":false,\"is_secret_dm_able\":false,\"is_blocked\":false,\"can_media_tag\":false,\"name\":\"rob skiff\",\"screen_name\":\"RobSkiff\",\"profile_image_url\":\"http:\\/\\/pbs.twimg.com\\/profile_images\\/568515549705953280\\/fdjcGF45_normal.jpeg\",\"profile_image_url_https\":\"https:\\/\\/pbs.twimg.com\\/profile_images\\/568515549705953280\\/fdjcGF45_normal.jpeg\",\"location\":\"st petersburg\",\"is_protected\":true,\"rounded_score\":0,\"social_proof\":0,\"connecting_user_count\":0,\"connecting_user_ids\":[],\"social_proofs_ordered\":[],\"tokens\":[],\"inline\":false}],\"topics\":[],\"events\":[],\"lists\":[],\"ordered_sections\":[],\"oneclick\":[],\"hashtags\":[],\"completed_in\":0.0,\"query\":\"skiff\"}"error: {}event: {}[[Prototype]]: Object
(anonymous) @ shared.js:150

I also got a bunch of runtime errors that immediately preceded this, which read as follows:

Unchecked runtime.lastError: The message port closed before a response was received.
home:1 Unchecked runtime.lastError: The message port closed before a response was received.

I don't know if they're related to Blue Blocker, but when I cleared the console so I'd only have the recreated error, these also showed, so figured I'd put them in just in case.

**Comment by DanielleMiu** [comment]
those runtime errors are from twitter's own code, so that's not my concern. this error is happening when you write "@skiffyandfanty" in the search bar? what browser (and version if you have it) are you using?

**Comment by shaunduke** [comment]
Running: Chrome (v 113.0.5672.127 64-bit). 

I get his error if I type other Twitter handles as well. I recreated it by just typing a word that came to mind (@noodle <-- I got to noo before the error popped). I did it again with a friend of mine's handle and again with another random newspaper handle (@bbc). So it doesn't appear to be dependent on which handle text I type.

**Comment by DanielleMiu** [comment]
but it only occurs when you write a handle ("@something") versus just a word ("something")?

**Comment by shaunduke** [comment]
Correct.
