### ISSUE TITLE
Bug: no longer collecting queue from search results

### ISSUE THREAD

**Issue by hollowleviathan** [kheina-com/Blue-Blocker#118]
Since yesterday, Blue Blocker does not seem to collect users in the queue directly from search results. Searching "bitcoin filter:blue_verified", the queue stays at 0.

Viewing individual users will still add them to the queue, and viewing a tweet with replies will collect from the tweet and/or replies.

**Comment by davidgerard** [comment]
can confirm results - doesn't add from search, adds from individual tweets. I'm seeing this on Firefox 113.0.2 Linux snap on Ubuntu

**Comment by pixelnull** [comment]
Also confirming v0.2.6 on FF 113.0 on Linux.

**Comment by MrAwesome** [comment]
Same, v0.2.6 on FF 113.0.1 on Linux. I'll try and dig around this weekend and see if I can figure out what's going on.

**Comment by MrAwesome** [comment]
Ok, put up a PR to fix this. (Funnily enough, it seems like the issue is unrelated to FireFox on Linux. I guess FF users on Linux are probably the most likely people to run and comment on a GH issue.)

Happy to iterate on the fix - it's my first time looking at this code.

**Comment by outabidagain** [comment]
this is still an issue. queue still isnt collecting on windows 10, chrome.

**Comment by pixelnull** [comment]
> this is still an issue. queue still isnt collecting on windows 10, chrome.

The update hasn't been released yet that I can see.

**Comment by DanielleMiu** [comment]
this was closed automatically by the pr merging to main, however the code hasn't been pushed to webstores yet. it'll go out in 0.2.7 likely, but we're working on updating the whole repository to typescript which is making it a little weird to push out updates right now.
