### ISSUE TITLE
Hide block notification

### ISSUE THREAD

**Issue by Emalcat** [kheina-com/Blue-Blocker#127]
I find this notification quite annoying, is there a way to disable it?
![image](https://github.com/kheina-com/Blue-Blocker/assets/88663610/8023d645-a13c-4d6f-8cc1-34cb14b10e9c)

**Comment by MrAwesome** [comment]
You should have a checkbox like this in the settings when you click on the extension icon - if you uncheck it, they'll go away. Does that work for you?

![2023-06-15_09:47:23](https://github.com/kheina-com/Blue-Blocker/assets/145945/d479dcb2-86e0-411c-af38-2c797f8ab6e2)
