### ISSUE TITLE
Feature Request: Blue Blocker on TamperMonkey

### ISSUE THREAD

**Issue by Baramanga** [kheina-com/Blue-Blocker#137]
Since Firefox Android allow TamperMonkey scripts, would you like to make it available through there? I think that would help on many other browsers as well

**Comment by choco-latin** [comment]
Just to say that this would be game changing for me, as I mostly use Twitter on my phone (but it looks like a lot of work)

**Comment by DanielleMiu** [comment]
I don't know what's all involved in getting a tamper monkey script working. bb relies on a service worker to do history tracking among other things

for now you can try one of these solutions for running blue blocker on mobile
https://github.com/kheina-com/Blue-Blocker/issues/132#issuecomment-1596235511
https://github.com/kheina-com/Blue-Blocker/issues/3#issuecomment-1547086961
