### ISSUE TITLE
Blue Blocker v0.2.7 on Firefox keeps blocking Matt Binder

### ISSUE THREAD

**Issue by ebelinski** [kheina-com/Blue-Blocker#138]
[Matt Binder](https://twitter.com/MattBinder) is a journalist who provides critical coverage of Elon Musk and Twitter. He has less than 1 million followers, but was forcibly given Twitter Blue like 1m+ users (see [here](https://twitter.com/mattbinder/status/1649885804607467523?s=46&t=9Xz4H93IqPk5Rg9umX8kLg)).

Blue Blocker v0.2.7 on Firefox keeps blocking @MattBinder. Worse yet, this is happening even though I'm following him and have "block people I follow" unchecked.

Blue Blocker does _not_ seem to be blocking other under-1m accounts that I follow (e.g. @/RailroadUnderg1), only @/MattBinder. I believe this should first be addressed as a bug, with a fix to fully prevent Blue Blocker from blocking users that I follow if "block people I follow" is unchecked.

Second, Blue Blocker should exclude @/MattBinder specifically from being blocked by default, since he did not pay for Twitter Blue. Maybe this could be done in the form of a default allowlist of sorts.

**Comment by DanielleMiu** [comment]
do you know what page he was queued from? for you page, timeline, search page, user page, tweet page, replies, etc?

**Comment by DanielleMiu** [comment]
so far I've been able to check the following endpoints: `HomeTimeline`, `HomeLatestTimeline`.
these I only checked by finding at least one "did not block user because you follow them" log message

I also checked the following: `search/typeahead.json`, `UserTweets`, `TweetDetail`, `SearchTimeline`
these I checked specifically by finding a "did not block Twitter Blue verified user Matt Binder (@MattBinder) because you follow them." log message

this leaves the two "For You" parsed endpoints: `timeline/home.json` and `search/adaptive.json` I don't know how these endpoints are triggered, they might even be deprecated at this point, but the rest appear to have the "user.legacy.following" populated correctly

**Comment by DanielleMiu** [comment]
even the "People" tab in the search results that Blue Blocker doesn't even parse appears to have `legacy.following` populated. it also still uses the `SearchTimeline` endpoint and not the adaptive one

**Comment by DanielleMiu** [comment]
@ebelinski were you using tweetdeck bychance?

**Comment by ebelinski** [comment]
Hey Danielle, thank you for looking into this. I think I've seen it happening from multiple pages, but the one where it happens all the time is https://twitter.com/MattBinder. If I just go to his profile, I get the blocked message at the bottom-left, usually multiple times. I was not using Tweetdeck.

<img width="1512" alt="image" src="https://github.com/kheina-com/Blue-Blocker/assets/4406614/5e5b9628-f599-4d14-a821-1947dbb83f11">


Here are some logs if this helps:

```
[Blue Blocker] parsed instructions path: 
Array(3) [ {…}, {…}, {…} ]
[instructions.js:97:10](moz-extension://681aea3d-897f-4c53-895b-1ef55ea7b63e/parsers/instructions.js)
[Blue Blocker] queued Matt Binder (@MattBinder) for a block due to Twitter Blue verified. [shared.js:179:10](moz-extension://681aea3d-897f-4c53-895b-1ef55ea7b63e/shared.js)
[Blue Blocker] did not block Twitter Blue verified user Abacus.AI (@abacusai) because they are verified through an affiliated organization. [shared.js:337:12](moz-extension://681aea3d-897f-4c53-895b-1ef55ea7b63e/shared.js)
[Blue Blocker] did not block Twitter Blue verified user CME Active Trader (@CMEActiveTrader) because they are verified through an affiliated organization. [shared.js:337:12](moz-extension://681aea3d-897f-4c53-895b-1ef55ea7b63e/shared.js)
[Blue Blocker] block request: 
Object { url: "https://twitter.com/i/api/1.1/blocks/create.json", body: "user_id=14931637", headers: {…}, method: "POST", credentials: "include" }
[shared.js:250:11](moz-extension://681aea3d-897f-4c53-895b-1ef55ea7b63e/shared.js)
[Blue Blocker] block request: 
Object { url: "https://twitter.com/i/api/1.1/blocks/create.json", body: "user_id=14931637", headers: {…}, method: "POST", credentials: "include" }
[shared.js:250:11](moz-extension://681aea3d-897f-4c53-895b-1ef55ea7b63e/shared.js)
[Blue Blocker] block request: 
Object { url: "https://twitter.com/i/api/1.1/blocks/create.json", body: "user_id=188793260", headers: {…}, method: "POST", credentials: "include" }
[shared.js:250:11](moz-extension://681aea3d-897f-4c53-895b-1ef55ea7b63e/shared.js)
[Blue Blocker] block response: 
Response { type: "basic", url: "https://twitter.com/i/api/1.1/blocks/create.json", redirected: false, status: 200, ok: true, statusText: "OK", headers: Headers(24), body: ReadableStream, bodyUsed: false }
[shared.js:253:12](moz-extension://681aea3d-897f-4c53-895b-1ef55ea7b63e/shared.js)
[Blue Blocker] blocked Nina Turner (@ninaturner) due to Twitter Blue verified. [shared.js:270:13](moz-extension://681aea3d-897f-4c53-895b-1ef55ea7b63e/shared.js)
[Blue Blocker] block response: 
Response { type: "basic", url: "https://twitter.com/i/api/1.1/blocks/create.json", redirected: false, status: 200, ok: true, statusText: "OK", headers: Headers(24), body: ReadableStream, bodyUsed: false }
[shared.js:253:12](moz-extension://681aea3d-897f-4c53-895b-1ef55ea7b63e/shared.js)
[Blue Blocker] blocked Matt Binder (@MattBinder) due to Twitter Blue verified. [shared.js:270:13](moz-extension://681aea3d-897f-4c53-895b-1ef55ea7b63e/shared.js)
[Blue Blocker] block response: 
Response { type: "basic", url: "https://twitter.com/i/api/1.1/blocks/create.json", redirected: false, status: 200, ok: true, statusText: "OK", headers: Headers(24), body: ReadableStream, bodyUsed: false }
[shared.js:253:12](moz-extension://681aea3d-897f-4c53-895b-1ef55ea7b63e/shared.js)
[Blue Blocker] blocked Matt Binder (@MattBinder) due to Twitter Blue verified. [shared.js:270:13](moz-extension://681aea3d-897f-4c53-895b-1ef55ea7b63e/shared.js)
[Blue Blocker] block request: 
Object { url: "https://twitter.com/i/api/1.1/blocks/create.json", body: "user_id=737049250366820356", headers: {…}, method: "POST", credentials: "include" }
[shared.js:250:11](moz-extension://681aea3d-897f-4c53-895b-1ef55ea7b63e/shared.js)
[Blue Blocker] block response: 
Response { type: "basic", url: "https://twitter.com/i/api/1.1/blocks/create.json", redirected: false, status: 200, ok: true, statusText: "OK", headers: Headers(24), body: ReadableStream, bodyUsed: false }
[shared.js:253:12](moz-extension://681aea3d-897f-4c53-895b-1ef55ea7b63e/shared.js)
[Blue Blocker] blocked Yasmine Mohammed 🦋 ياسمين محمد (@YasMohammedxx) due to Twitter Blue verified. [shared.js:270:13](moz-extension://681aea3d-897f-4c53-895b-1ef55ea7b63e/shared.js)
[Blue Blocker] block request: 
Object { url: "https://twitter.com/i/api/1.1/blocks/create.json", body: "user_id=892121309467029507", headers: {…}, method: "POST", credentials: "include" }
[shared.js:250:11](moz-extension://681aea3d-897f-4c53-895b-1ef55ea7b63e/shared.js)
[Blue Blocker] block response: 
Response { type: "basic", url: "https://twitter.com/i/api/1.1/blocks/create.json", redirected: false, status: 200, ok: true, statusText: "OK", headers: Headers(24), body: ReadableStream, bodyUsed: false }
```

**Comment by ebelinski** [comment]
I don't know if this makes a difference, but I'm using Twitter in a [Firefox Container](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/).

**Comment by DanielleMiu** [comment]
and the queue was empty prior to visiting his page?

**Comment by ebelinski** [comment]
I'm not sure, what queue are you referring to?

**Comment by DanielleMiu** [comment]
> I don't know if this makes a difference, but I'm using Twitter in a [Firefox Container](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/).

oh I have no clue how that works, but it might. could you copy that `parsed instructions path:` object? firefox should have a way to copy object if you right click on it

**Comment by DanielleMiu** [comment]
> I'm not sure, what queue are you referring to?

addon uses an internal queue to slowly block users so it doesn't hit the twitter api rate limiter. you can view the queue count from the context menu (clicking the extension icon) or view the whole queue itself by clicking view next to the count. I don't think it matters if he was queued previously, though, since it was trying to add him again regardless

**Comment by ebelinski** [comment]
I switched over to my other Twitter account that is not inside a Firefox Container. Here is the parsed object from a new session where Blue Blocker again blocked MattBinder:

[[Blue Blocker] parsed instructions path.txt](https://github.com/kheina-com/Blue-Blocker/files/11793170/Blue.Blocker.parsed.instructions.path.txt)

**Comment by DanielleMiu** [comment]
thanks, give me a sec to look through this

**Comment by DanielleMiu** [comment]
in your whole response object, the `following` key simply doesn't exist

here's the user object I get when I view his page:
```json
{
	"__typename": "User",
	"id": "VXNlcjoxNDkzMTYzNw==",
	"rest_id": "14931637",
	"affiliates_highlighted_label": {},
	"has_graduated_access": true,
	"is_blue_verified": true,
	"profile_image_shape": "Circle",
	"legacy": {
		"following": true,  // clearly shows that I follow him
		"can_dm": true,
		"can_media_tag": true,
		"created_at": "Wed May 28 07:59:20 +0000 2008",
		"default_profile": true,
		"default_profile_image": false,
		"description": "host: https://t.co/MuuVDPKViz & https://t.co/8tcAihCMq5 // video: https://t.co/TH6pyUtFb7 // newsletter: https://t.co/rDJSuSdyBI // reporter: @mashable // @majorityfm thursdays",
		"entities": <deleted because it's huge>,
		"fast_followers_count": 0,
		"favourites_count": 128653,
		"followers_count": 147651,
		"friends_count": 697,
		"has_custom_timelines": true,
		"is_translator": false,
		"listed_count": 1563,
		"location": "New York, New York",
		"media_count": 5784,
		"name": "Matt Binder",
		"normal_followers_count": 147651,
		"pinned_tweet_ids_str": [
			"1649884329240141828"
		],
		"possibly_sensitive": false,
		"profile_banner_url": "https://pbs.twimg.com/profile_banners/14931637/1423690374",
		"profile_image_url_https": "https://pbs.twimg.com/profile_images/1177635972466515968/wagz7QQt_normal.jpg",
		"profile_interstitial_type": "",
		"screen_name": "MattBinder",
		"statuses_count": 61209,
		"translator_type": "none",
		"url": "https://t.co/VA8qafZs1D",
		"verified": false,
		"want_retweets": true,
		"withheld_in_countries": []
	}
}
```

and now the response from your logs:
```json
{
	"__typename": "User",
	"id": "VXNlcjoxNDkzMTYzNw==",
	"rest_id": "14931637",
	"affiliates_highlighted_label": {},
	"has_graduated_access": true,
	"is_blue_verified": true,
	"profile_image_shape": "Circle",
	"legacy": {
		"can_dm": true,  // there is no "following" key here
		"can_media_tag": true,
		"created_at": "Wed May 28 07:59:20 +0000 2008",
		"default_profile": true,
		"default_profile_image": false,
		"description": "host: https://t.co/MuuVDPKViz & https://t.co/8tcAihCMq5 // video: https://t.co/TH6pyUtFb7 // newsletter: https://t.co/rDJSuSdyBI // reporter: @mashable // @majorityfm thursdays",
		"entities": <again, huge>,
		"fast_followers_count": 0,
		"favourites_count": 128653,
		"followers_count": 147652,
		"friends_count": 697,
		"has_custom_timelines": true,
		"is_translator": false,
		"listed_count": 1563,
		"location": "New York, New York",
		"media_count": 5784,
		"name": "Matt Binder",
		"normal_followers_count": 147652,
		"pinned_tweet_ids_str": [
			"1649884329240141828"
		],
		"possibly_sensitive": false,
		"profile_banner_url": "https://pbs.twimg.com/profile_banners/14931637/1423690374",
		"profile_image_url_https": "https://pbs.twimg.com/profile_images/1177635972466515968/wagz7QQt_normal.jpg",
		"profile_interstitial_type": "",
		"screen_name": "MattBinder",
		"statuses_count": 61209,
		"translator_type": "none",
		"url": "https://t.co/VA8qafZs1D",
		"verified": false,
		"want_retweets": false,
		"withheld_in_countries": []
	}
}
```

**Comment by ebelinski** [comment]
That's very strange, I'm not sure what's going on. But it's clearly happened me multiple times now where Matt Binder gets blocked, I unblock and re-follow, then he gets blocked again. I also _think_ he might be getting blocked only when I follow him, though I'm not sure.

I tried capturing a video of this all happening but for whatever reason, Blue Blocker is not blocking any more Twitter Blue users for me right now.

**Comment by DanielleMiu** [comment]
for now I can only recommend clicking the "undo" button on the popup when he gets blocked next. this will add him to a safelist and he won't get blocked again until I can make a fix for this. hopefully in the next day or so

**Comment by ebelinski** [comment]
Sounds good. For what it's worth, I restarted Firefox, and now Blue Blocker seems to be operating correctly. It's blocking other users but not Matt Binder (I see the console message `[Blue Blocker] did not block Twitter Blue verified user Matt Binder (@MattBinder) because you follow them.`). I'll try to record a video of it the next time it happens and post logs again.

**Comment by DanielleMiu** [comment]
had you just followed him?

**Comment by DanielleMiu** [comment]
ie, in the same session

**Comment by ebelinski** [comment]
I was follwing him in the past. But there were instances today where he was blocked, I unblocked and refollowed, then he got blocked again. Maybe Blue Blocker queued the block after I unblocked but before I hit follow?

**Comment by DanielleMiu** [comment]
I don't believe so, unless you got a batch of tweets inbetween those two things happening? but that wouldn't explain how he got blocked in the first place.

**Comment by DanielleMiu** [comment]
the thing is, twitter's api (and honestly, many others) likes to omit variables in json responses when they're a zero value like `false`, `0`, `""`, etc. it looks like they do that with following as well. if you're not following a user, the key is omitted entirely. idk how to detect when you're actually not following a person versus the api just fucking up

**Comment by ebelinski** [comment]
I think some of my problems could be related to Firefox Containers after all. I found consistently that if I don't follow Matt on my non-container Twitter account, but I follow him on my container Twitter account, when I visit his profile on the container account, I get the "blocked Matt Binder" message, but he doesn't show up as blocked in the container account, he shows up as blocked in the non-container account (so, blocked on the wrong account).

See video: https://drive.google.com/file/d/1HlO1b8cEVinaUMnXmrCDgVX2-bbNHdoT/view?usp=sharing

Not sure if all of the weirdness I've been experiencing vis-a-vis Matt's account is related to Firefox Containers, but at least this is the one scenario I'm able to reproduce right now.

**Comment by ebelinski** [comment]
Anyway, thank you so much for looking into this.

**Comment by DanielleMiu** [comment]
I think that might be involved too. the headers used to block could technically be different than those used to make requests since they're stored globally for the extension and updated whenever a requested is processed (there are the "updated headers" debug messages in the console when this happens)

the same is true of the queue, so it could be that the container account isn't following, and queues him for blocking, and the non-container account is the one processing the queue and sends the block request

**Comment by DanielleMiu** [comment]
ok, having seen the video, it really looks like that's what's going on. I wasn't really thinking about users having multiple accounts running simultaneously when designing the infrastructure of the queuing system, so I guess it breaks down a little bit when you have more than one account open at the same time

**Comment by rougetimelord** [comment]
Going to link this in with #203, and close this specific issue
