### ISSUE TITLE
Does secret behavior. 

### ISSUE THREAD

**Issue by CountPatagium** [kheina-com/Blue-Blocker#14]
It blocks people with NFT avatars, which is not disclosed in the title or description. This should be either a separate option or a separate plugin.

**Comment by rlyshw** [comment]
it is a separate option https://github.com/kheina-com/Blue-Blocker/blob/bdf0883da488282b23e5165959a682161091b0fa/chrome/options.js#L36

**Comment by CountPatagium** [comment]
That's where it is in the code, which is the only way I knew that it was doing that. The option does not appear in the UI, nor does the name or description mention this additional behavior.

**Comment by rlyshw** [comment]
should be exposed in the ui. i'll take a look... btw this repo might be abandoned so I'm forking it and intend to republish under my version's listing

**Comment by PhantomGamers** [comment]
It does appear as an option, at least on Firefox.

**Comment by DanielleMiu** [comment]
functionality is optional and defaults to false
https://github.com/kheina-com/Blue-Blocker/blob/47ee91acd42bbbffd883b8256fe6c1cc89f22aba/shared.js#L16

**Comment by CountPatagium** [comment]
pre

> It does appear as an option, at least on Firefox.

Where? 

<img width="730" alt="Untitled" src="https://user-images.githubusercontent.com/59474420/234558579-ba99aad4-ccb8-4a9d-8e2e-f537fda76c26.png">

**Comment by CountPatagium** [comment]
For folks just quoting the code, thanks, but maybe show me in the UI where it is showing up, because it's not in mine. Firefox 112.0.1 (64-bit) on OS X

**Comment by CountPatagium** [comment]
My bad. It's the mozilla interface for the plugin. My plugin icon was hidden under the "Extensions" Icon for some reason. That said, I only see the first, third and last options.

**Comment by rlyshw** [comment]
update was just pushed yesterday. check the plugin store to get the newest version.
