### ISSUE TITLE
Visiting a verified profile does not add it to the queue if the user has no tweets

### ISSUE THREAD

**Issue by burpen** [kheina-com/Blue-Blocker#140]
If I navigate to a verified profile and it meets the criteria for blocking based on my current settings, it fails to be added to the queue if the user has no tweets listed in the Tweets tab. The extension does not log any messages about the profile like one might expect.

If I view the Tweets tab, the console shows parse data with a `TimelineAddEntries` object that doesn't contain any tweet entries. If I view the Replies tab, even if there are reply tweets visible on the page, the extension doesn't log any parse data. To get the user into the queue I have to go to one of their reply tweets or a tweet that they have replied to and make sure that their reply is visible.

I can provide an example profile via DM if it's helpful (doesn't feel right blasting out a link to a profile from an issue).

**Comment by DanielleMiu** [comment]
this is the expected current behavior. this is not technically a bug since it's known behavior, but what you're requesting specifically is to add the `UserByScreenName` endpoint to the requests being parsed by blue blocker. this is the api call that returns profile information when you navigate to a user page.

**Comment by rougetimelord** [comment]
When the document first loads, `window.__INITIAL_STATE__.users.entities` contains the user objects we're looking for, but at some point it gets deleted. Idk how feasible it is to grab it while it exists tbh
