### ISSUE TITLE
i don't know what happened, the extension just told me to put this here

### ISSUE THREAD

**Issue by HEYimHeroic** [kheina-com/Blue-Blocker#142]
was browsing twitter. all of a sudden:
![image](https://github.com/kheina-com/Blue-Blocker/assets/48461034/7f432946-bf3b-4fde-bff1-f67f187f1c27)
`{
    "body_str": "{\"errors\":[{\"message\":\"Timeout: Unspecified\",\"locations\":[{\"line\":5,\"column\":3}],\"path\":[\"threaded_conversation_with_injections_v2\"],\"extensions\":{\"name\":\"TimeoutError\",\"source\":\"Server\",\"retry_after\":0,\"code\":29,\"kind\":\"ServiceLevel\",\"tracing\":{\"trace_id\":\"ca1592ac02431e6c\"}},\"code\":29,\"kind\":\"ServiceLevel\",\"name\":\"TimeoutError\",\"source\":\"Server\",\"retry_after\":0,\"tracing\":{\"trace_id\":\"ca1592ac02431e6c\"}}],\"data\":{}}",
    "error": {},
    "event": {}
}`

then it happened again shortly after:
`{
    "body_str": "{\"data\":{\"home\":{}}}",
    "error": {},
    "event": {}
}`

hope that's enough! don't really know what else to do. i was just browsing a thread clicking on images so... i don't really know what else to mention here. refreshed and everything went back to normal

**Comment by DanielleMiu** [comment]
thanks! This is the error message that occurs for unknown errors. in this case it looks like twitter sent an error response to one of its requests. nothing to really worry about but good for us to handle it better

**Comment by DanielleMiu** [comment]
fixed in https://github.com/kheina-com/Blue-Blocker/pull/143
