### ISSUE TITLE
Make queue interval configurable

### ISSUE THREAD

**Issue by PhantomGamers** [kheina-com/Blue-Blocker#16]
#10 made it so users who are to be blocked get added to a queue and then each user in the queue is blocked in 5 second intervals. This is to avoid being signed out by the API, however I find 5 seconds is a bit too long, especially on threads with many blue verified users.

In my testing even lowering it to 1.5 seconds prevented the sign out most of the time, however I think it would be better to just have this interval be configurable.

Alternatively the 5 second interval would not be as bad if the queue was stored independent of the page, so as a user is navigating around Twitter the queue will continue to be processed in the background, but I think this might be more difficult to implement.

**Comment by DanielleMiu** [comment]
in addition to this, it might be a good idea to store the queue in local storage. also wouldn't hurt to add a little bit of randomness to the wait time
