### ISSUE TITLE
issue: blue check in quote tweet in search results not being blocked

### ISSUE THREAD

**Issue by Baramanga** [kheina-com/Blue-Blocker#163]
Yeah so when I open search result to mass block, the extension doesn't collect the blue check accounts being quote tweeted

**Comment by DanielleMiu** [comment]
hey, thanks for submitting an issue! twitter sometimes varies what queries they use and how they use them in different places so
1. could you please provide what [browser](https://github.com/kheina-com/Blue-Blocker/wiki/How-To-Make-An-Issue#browser-information) and [extension](https://github.com/kheina-com/Blue-Blocker/wiki/How-To-Make-An-Issue#extension-version) version you have?
2. was this on twitter.com or tweetdeck?
3. if it was on twitter.com was this is the top or latest tab or another tab?

and generally anything else you might think is useful, thanks!

**Comment by Baramanga** [comment]
> hey, thanks for submitting an issue! twitter sometimes varies what queries they use and how they use them in different places so
> 
>     1. could you please provide what [browser](https://github.com/kheina-com/Blue-Blocker/wiki/How-To-Make-An-Issue#browser-information) and [extension](https://github.com/kheina-com/Blue-Blocker/wiki/How-To-Make-An-Issue#extension-version) version you have?
> 
>     2. was this on twitter.com or tweetdeck?
> 
>     3. if it was on twitter.com was this is the top or latest tab or another tab?
> 
> 
> and generally anything else you might think is useful, thanks!

This is on Firefox, twitter.com, extension version 0.3.2, both top and latest tabs

**Comment by DanielleMiu** [comment]
it seems like I'm not able to replicate what you're seeing. is it because your follower threshold is too low and they're larger accounts?

if you have confirmation of one of these not occurring, blue blocker outputs `[Blue Blocker] parsed instructions path: 
Array` debug messages, copying one of those objects with the tweet in it would help a lot

**Comment by rougetimelord** [comment]
Stale and no reproduction
