### ISSUE TITLE
Feature: suggested Blue Check account not collected

### ISSUE THREAD

**Issue by Baramanga** [kheina-com/Blue-Blocker#164]
blue checks suggested when visit an account profile isn't collected. This is very useful fro collecting multiple of them quickly

**Comment by DanielleMiu** [comment]
currently blue blocker only scans tweets to collect users to block, since this is where 99% of people see users. but yeah this would be cool for sure

**Comment by rougetimelord** [comment]
Endpoint: `api/1.1/users/recommendations.json`
