### ISSUE TITLE
Bug: promoted Tweet not blocked on Firefox, twitter.com, home Following page

### ISSUE THREAD

**Issue by Baramanga** [kheina-com/Blue-Blocker#168]
Yeah so it's not collecting promoted tweet here even when I enabled it

**Comment by DanielleMiu** [comment]
when you open the developer console, the user that posted the tweet isn't listed as having been queued?
if not, is there a debug message labelled `[Blue Blocker] parsed instructions path: Array` from when it should have been queued?

**Comment by rougetimelord** [comment]
Can't repro, and not enough info to diagnose.
