### ISSUE TITLE
Request: Promote Tweet overwrite

### ISSUE THREAD

**Issue by Baramanga** [kheina-com/Blue-Blocker#175]
So here's the thing: not everyone who is "verified" on my timeline is bad and I would wanna apply the verified filter with about 1000 follower limit. However, I will block EVERYONE who is in promoted tweet regardless of follower count. Is there a way to have a "promoted tweet" overwrite, like block all account who promoted tweets regardless of follower count while leaving the rest of my timeline to a finer filter?

Thank you.

**Comment by DanielleMiu** [comment]
this is how it currently works
