### ISSUE TITLE
Immediately remove Blue users from the DOM?

### ISSUE THREAD

**Issue by Aurailus** [kheina-com/Blue-Blocker#179]
I love this extension, but I find it unfortunate that when I click through to the comments of a popular tweet I still see a ton of blue users because of the time it takes for blocks to go through. It would be nice if as soon as Blue users appear on the page, the extension queued their block AND removed their post from the DOM, so that you would just never see them. Just a thought!

**Comment by DanielleMiu** [comment]
I'm currently thinking of a way that blue blocker can modify api responses before [sending them back to the frontend](https://github.com/kheina-com/Blue-Blocker/blob/af9503a397fc3c305ca463391f63ee4378a26457/src/injected/inject.ts#L46) to remove things like ads and blue users, but that would likely require a pretty serious overhaul to how things are done now.
in the mean time, you can use https://github.com/BlueLiteBlocker/BlueLiteBlocker. I haven't looked into it, but I don't think there's anything preventing the two extensions from working together

**Comment by Aurailus** [comment]
Ah, I didn't know this was a thing. Thank you!

**Comment by DanielleMiu** [comment]
closing in favor of #17
