### ISSUE TITLE
Account Specific Toggle

### ISSUE THREAD

**Issue by Stuart1998** [kheina-com/Blue-Blocker#180]
I run several different twitter accounts, two personals as well as several accounts for hobby projects ran by multiple people. I only want blueblocker running on one of my personal accounts, on the other personal account it has a higher rate of blocking people I don't want blocked and it shouldn't be blocking anyone on the accounts I use that are ran by multiple people. I can manually toggle it on and off but there's a high likelihood of me forgetting to toggle it whenever I switch accounts.

**Comment by DanielleMiu** [comment]
this is a known issue (see #87), I just haven't thought of a neat way to keep track of multiple sets of credentials and how to know when to switch, and how the ui would react to such a change

**Comment by rougetimelord** [comment]
Going to close this because afaik #203 is the same but has more discussion of how to implement
