### ISSUE TITLE
Replies to tweet not loading during blocking?

### ISSUE THREAD

**Issue by sonicdoommario** [kheina-com/Blue-Blocker#183]
Not sure if this is a biproduct of the meltdown Twitter had with the rate-limiting over the weekend, but when I browse the replies to the tweet to queue up several users to be blocked, I get the "Something went wrong, try again" message from Twitter when viewing replies to a tweet. The rest of Twitter still works fine (viewing someone's profile, loading quote tweets, etc), but during the time when accounts are being blocked, I haven't been able to view replies to a tweet, normally they load back up once the queue empties out or gets pretty low.

Anyone else encountering this? Or is Twitter just still a landmine where looking at the site funny will blow something up?

**Comment by DanielleMiu** [comment]
blue blocker doesn't modify or block requests being made so this sounds like a twitter issue
