### ISSUE TITLE
Can't use in combination with DimidenGD's OldTwitter extension

### ISSUE THREAD

**Issue by millionsofplayers** [kheina-com/Blue-Blocker#185]

**Comment by DanielleMiu** [comment]
known issue, see #173. in short, requires changes in old twitter, which I made an issue for as well if you want to +1 or comment here: https://github.com/dimdenGD/OldTwitter/issues/88

I'm working on a lot of big changes for 0.4.0 including arbitrary integration support. once that's done I may make a pr against old twitter myself to add support for blue blocker
