### ISSUE TITLE
Blue Blocker doesn't work on firefox prior to vresion 101

### ISSUE THREAD

**Issue by kheina** [kheina-com/Blue-Blocker#190]
requires storage onChanged events https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea/onChanged

**Comment by rougetimelord** [comment]
Going to go ahead and close this, according to [caniuse](https://caniuse.com/usage-table) the percentage of users affected is way under 0.5%
