### ISSUE TITLE
Ability to replace the X branding with the correct Twitter logo?

### ISSUE THREAD

**Issue by Reonu** [kheina-com/Blue-Blocker#193]
so I know this extension has a very specific purpose right now but I assume that the venn diagram of people who want to block Blue users and people who fucking hate the X rebranding is has an almost 100% overlap so I think the feature would be very welcome!

**Comment by DanielleMiu** [comment]
this is definitely not in the scope of Blue Blocker, but I imagine control panel for twitter and likely also better twitter (if I remember that extension correctly) will add options for this soon
