### ISSUE TITLE
Twitter Blue users can now bypass being blocked

### ISSUE THREAD

**Issue by jackboykin** [kheina-com/Blue-Blocker#195]
a twitter update has enabled a new option for blue subs to hide their checkmark. Is there any way to update the extension to detect blue subs that hide the check?

**Comment by insin** [comment]
Don't know if they'll get round to fixing this, but this is the user entity data for someone who turned their check off - `can_highlight_tweets` is still `true`

![image](https://github.com/kheina-com/Blue-Blocker/assets/226692/1819d4c2-eceb-474c-85c2-1807fdffceba)

**Comment by DanielleMiu** [comment]
yeah seems like there's a few things we can check to see if they're blue users, another notable key would be `is_edit_eligible` within `edit_control`. hopefully something is a reliable indicator of blue status

**Comment by DanielleMiu** [comment]
does anyone have any good examples of a known blue user that has disabled their checkmark?

**Comment by cjshrader** [comment]
This guy made this long post, so he's definitely blue, and he has the checkmark turned off: https://twitter.com/Baconfromhell/status/1686704275660181505

**Comment by DanielleMiu** [comment]
beautiful, thank you, I'll look into this when I can, definitely a prio

**Comment by trtlemediocre** [comment]
Hi, ran across this and I think I've got some more data points for you; the OP of https://twitter.com/unpuppable/status/1690101699698999296 has been hiding blue checks, and apparently hidden ones still showed up under verified notifications (https://twitter.com/unpuppable/status/1690333377142943746), so the hidden replies on there have a mix of open blues and hidden blues.

I also had a poke around on the network tab for the user page, and it looks like the UserByScreenName request still gets the "verification_info" field, even with a hidden check (from https://twitter.com/knowmiun):
![image](https://github.com/kheina-com/Blue-Blocker/assets/136266915/4a2d7fcf-481a-4e81-9375-043a45acb905)
It doesn't look like this appears in all "User" object responses, but it might be a useful indicator when it does.

**Comment by kheina** [comment]
> Hi, ran across this and I think I've got some more data points for you; the OP of https://twitter.com/unpuppable/status/1690101699698999296 has been hiding blue checks, and apparently hidden ones still showed up under verified notifications (https://twitter.com/unpuppable/status/1690333377142943746), so the hidden replies on there have a mix of open blues and hidden blues.
> 
> I also had a poke around on the network tab for the user page, and it looks like the UserByScreenName request still gets the "verification_info" field, even with a hidden check (from https://twitter.com/knowmiun): ![image](https://user-images.githubusercontent.com/136266915/260263497-4a2d7fcf-481a-4e81-9375-043a45acb905.png) It doesn't look like this appears in all "User" object responses, but it might be a useful indicator when it does.

that's good to know. unfortunately this info doesn't appear in tweet responses, if I remember correctly. but a good field to double check with during implementation

**Comment by cooljeanius** [comment]
> a twitter update has enabled a new option for blue subs to hide their checkmark. Is there any way to update the extension to detect blue subs that hide the check?

Note that this feature is going to be going away again:
https://www.theverge.com/2024/4/11/24127906/x-premium-users-can-no-longer-hide-their-blue-checks

**Comment by rougetimelord** [comment]
Well that certainly makes our work easier!

**Comment by rougetimelord** [comment]
> > a twitter update has enabled a new option for blue subs to hide their checkmark. Is there any way to update the extension to detect blue subs that hide the check?
> 
> Note that this feature is going to be going away again: https://www.theverge.com/2024/4/11/24127906/x-premium-users-can-no-longer-hide-their-blue-checks

I think that this got rolled out? I'm seeing a lot of people who did not have checkmarks suddenly having checkmarks again.

**Comment by cjshrader** [comment]
It did get rolled out, but also note that anyone with 2500 Twitter Blue followers automatically gets the blue check for free now, even if they didn't want it. A lot of people you're seeing with a check are because of that as well.

**Comment by cooljeanius** [comment]
> It did get rolled out, but also note that anyone with 2500 Twitter Blue followers automatically gets the blue check for free now, even if they didn't want it. A lot of people you're seeing with a check are because of that as well.

That's the thing that's tracked in #241 isn't it?

**Comment by cjshrader** [comment]
> That's the thing that's tracked in #241 isn't it?

Yep, I believe so

**Comment by rougetimelord** [comment]
I'm going to go ahead and close this issue as completed since blue users can no longer hide their checkmarks.
