### ISSUE TITLE
Settings option not available on Firefox

### ISSUE THREAD

**Issue by ashleyconnor** [kheina-com/Blue-Blocker#2]
Howdy

Looks like the settings option to block twitter blue followers isn't available in Firefox.

<img width="696" alt="Screenshot 2023-04-21 at 2 18 31 pm" src="https://user-images.githubusercontent.com/458214/233736399-58d6723c-3f83-4786-ae13-17cfc107cc69.png">

**Comment by mikkelens** [comment]
It's there: you just need to find it in your extensions icon (top right by default) and click it.
![image](https://user-images.githubusercontent.com/31762830/233753739-1a1547c6-294d-47a3-b605-06ad5e7582b8.png)
![image](https://user-images.githubusercontent.com/31762830/233753742-63a7cb6d-1bb6-466f-b3b1-f574264ff231.png)
