### ISSUE TITLE
Block Queue Import by UserId

### ISSUE THREAD

**Issue by roland-detterbeck** [kheina-com/Blue-Blocker#200]
Hi,

I wanted to import a blocklist but I only have the users ids, not their screen name.

Currently the import ignores the user_id in the json and blocks by screen name. 

Can you fix this or is there an easy way to bulk fetch screen names for ids?

Thanks!

**Comment by kheina** [comment]
hey roland, the only metric needed for blocking is the user_id, it is hard required. the others are needed for the import, but not needed to actually send the block request. if you want, you can make a script to convert the list that you have into a json matching the `BlockUser[]` definition in the import dialogue and it should work

**Comment by roland-detterbeck** [comment]
hi,
i imported a json like this:
`{
	user_id: USER_ID_OF_THE_USER,
	user: { name: SOME_DUMMY_STRING, screen_name: SCREEN_NAME_OF_ANOTHER_USER },
	reason: 0
}`
and the addon blocked "ANOTHER_USER" not "THE_USER".
what am i missing? :)

**Comment by kheina** [comment]
here is the code that actually performs the block:

https://github.com/kheina-com/Blue-Blocker/blob/f6db6561f89b8f3c29a9a181b6d81534208eab09/src/shared.ts#L255-L350

`user_id` is the only value that's actually used in the block request via the api. **`user.name` and `user.screen_name` are only used for reporting and history.** they are not used in the actual request, but are rather what are displayed in the "blocked X user" popup and the history page. they are purely for your own records.

if you'd like, you can test this bychecking which of the users in your example were blocked. was the actual owner of `SCREEN_NAME_OF_ANOTHER_USER` blocked or was in the account of `USER_ID_OF_THE_USER`?

**Comment by roland-detterbeck** [comment]
the owner of the screen name got blocked.

**Comment by roland-detterbeck** [comment]
ok i will check again later after my block queue is finished ;)

**Comment by roland-detterbeck** [comment]
ok, it works like it should. the user gets blocked by id. looks like the wrong username in the history tricked me.
