### ISSUE TITLE
Hide posts from queued accounts

### ISSUE THREAD

**Issue by kolgza** [kheina-com/Blue-Blocker#201]
Currently, the user must wait for the queue to finish before not seeing posts from queued accounts. [BlueLiteBlocker](https://github.com/BlueLiteBlocker/BlueLiteBlocker/tree/master) solves this by simply hiding all posts from Twitter Blue users, although it does not block accounts.

**Comment by kheina** [comment]
closing as it's a duplicate of #17, but I would recommend simply running both extensions for now. I doubt I'll add this as a feature and blue blocker and blueliteblocker shouldn't interfere with each other
