### ISSUE TITLE
Mass Mute people

### ISSUE THREAD

**Issue by yoshimo** [kheina-com/Blue-Blocker#205]
It would be great if we could feed a list of account names that should be muted into the Addon and it goes through the profiles and mutes them.

This would also make it easier to see what people you still need to convince to switch to a different place.

**Comment by kheina** [comment]
Hi, you can import users into the queue by going to the queue page (found by opening the settings menu by clicking the extension icon in your browser toolbar and clicking view next to the queue counter) and clicking import on the right side of the page. You can follow the instructions on that page to import a json file of users.

if you're more technical there are some various details on what's necessary or not to build your own json file to import in this thread here: #200

**Comment by yoshimo** [comment]
I dont want to block them but mute, still a small difference on X.
