### ISSUE TITLE
Feature request: Hide "this post is from an account you've blocked/muted"

### ISSUE THREAD

**Issue by juliloving** [kheina-com/Blue-Blocker#212]
It really clutters the reply feed for me, and I'm sure I'm not the only one![Screenshot_20231003_150205_Kiwi Browser.jpg](https://github.com/kheina-com/Blue-Blocker/assets/85190590/ff7ad20f-fc0f-4314-b0d0-efeeebef83f0)

**Comment by darkpixlz** [comment]
+1

**Comment by CLMagnus** [comment]
+1

**Comment by cooljeanius** [comment]
I think this is a dup of #80

**Comment by cooljeanius** [comment]
> I think this is a dup of #80

...yeah, closing as a dup of #80.
