### ISSUE TITLE
Could not parse tweet: Tombstone

### ISSUE THREAD

**Issue by rougetimelord** [kheina-com/Blue-Blocker#219]
If the extension gets an API response with `type: TweetTombstone` the object gets passed to handleTweetObject which gracefully fails here:
https://github.com/kheina-com/Blue-Blocker/blob/d301118d32d5bef801c47df025dfd54857a95174/src/parsers/instructions.ts#L73

The TweetTombstone object looks like this:
```JSON
{
    "__typename": "TweetTombstone",
    "tombstone": {
        "__typename": "TextTombstone",
        "text": {
            "rtl": false,
            "text": "You’re unable to view this Post because this account owner limits who can view their Posts. Learn more",
            "entities": [
                {
                    "fromIndex": 92,
                    "toIndex": 102,
                    "ref": {
                        "type": "TimelineUrl",
                        "url": "https://help.twitter.com/rules-and-policies/notices-on-twitter",
                        "urlType": "ExternalUrl"
                    }
                }
            ]
        }
    }
}
```

**Comment by rougetimelord** [comment]
Feel free to assign this issue to me, I'm working on a fix right now and just wanted an issue number to reference.

**Comment by cooljeanius** [comment]
> Feel free to assign this issue to me, I'm working on a fix right now and just wanted an issue number to reference.

OK, done.
