### ISSUE TITLE
Check if "block users with NFT avatars" option still does anything after removal of NFT support

### ISSUE THREAD

**Issue by cooljeanius** [kheina-com/Blue-Blocker#228]
See: https://web3isgoinggreat.com/?id=twitter-removes-nft-profile-picture-support

**Comment by rougetimelord** [comment]
Checking back in, I don't think it does anything anymore. I haven't seen any accounts that still have the hexagon profile pictures since the feature was dropped, and all of the accounts that I found that used to have them no longer do.
