### ISSUE TITLE
Not blocking first batch on direct links

### ISSUE THREAD

**Issue by KDederichs** [kheina-com/Blue-Blocker#23]
If you open up a twitter link from somewhere the plugin won't parse and block the first few replies that are loaded when you open the link.

**Comment by DanielleMiu** [comment]
I don't know why this was immediately closed, but I've noticed this issue as well. I think it has something to do with the first request being made before the inject script has a chance to run. however, I have not fully looked into it yet

**Comment by KDederichs** [comment]
well I immediately closed it cause when I noticed it the addon wasn't running :D
So I thought better close than raise false flags.

**Comment by DanielleMiu** [comment]
not possible on firefox, not an issue on chrome
