### ISSUE TITLE
Feature Request: Block Users Based on Keywords in Bio/Username

### ISSUE THREAD

**Issue by Miigle-Rose** [kheina-com/Blue-Blocker#230]
An autoblocker with the ability to be expanded to block/mute anybody with words in their bios (selected by the user, preferably) would most likely make comment sections a lot more tolerable.

**Comment by Miigle-Rose** [comment]
I've seen that there was a feature request for this already, my apologies (although if you want a different feature request I would also suggest a way to autoblock accounts without profile pictures/bios at all?)

**Comment by cooljeanius** [comment]
> I've seen that there was a feature request for this already, my apologies

yeah, #133 for the bio part, and #114 for the username part

> (although if you want a different feature request I would also suggest a way to autoblock accounts without profile pictures/bios at all?)

Sure, I guess that could work...

**Comment by cooljeanius** [comment]
see also PR #222 as well

**Comment by rougetimelord** [comment]
I think that this feature would seriously change the intent of this extension as a whole. (As I understand it) Currently the intention of the extension is to automatically block as many Premium users as can be feasibly detected. I think there is a discussion to be had if that is all we want from the extension, but as it stands I feel that this feature request is out of scope.

**Comment by cooljeanius** [comment]
> I think that this feature would seriously change the intent of this extension as a whole. (As I understand it) Currently the intention of the extension is to automatically block as many Premium users as can be feasibly detected. I think there is a discussion to be had if that is all we want from the extension, but as it stands I feel that this feature request is out of scope.

Yeah I kind of agree, actually; I'll close this now
