### ISSUE TITLE
Blocking the firstname-bunchanumbers accounts

### ISSUE THREAD

**Issue by QMulative** [kheina-com/Blue-Blocker#235]
1. Is there anything on the schedule about blocking right-wing bot accounts?  They follow a very simple pattern of having a first name, followed by a bunch of numbers.

2. If that's possible, then I'd also like to automatically block anyone with 88 or 1488 in their profile names as well. 

3. A newer bot tactic seems to be creating a new account with a stock or stolen profile picture of a woman in a swimsuit or tight clothes, and then following 4000-5000 people, about 50 of whom will follow back without thinking.  Would it be possible to automatically block those when they show up in notifications?

**Comment by rougetimelord** [comment]
As discussed in #230 this is currently out of scope for the extension.

Number 1 would be difficult to implement without a large list of first names. Number 2 would be easy to implement but is likely to have false positives, eg. the number 88 has significance in Chinese numerology. Number 3 would also be hard to implement, interpreting clothing from a picture would most likely require some level of machine learning.

I would look into [soupcan](https://github.com/bethylamine/soupcan) for the first two.

**Comment by cooljeanius** [comment]
> As discussed in #230 this is currently out of scope for the extension.
> 
> Number 1 would be difficult to implement without a large list of first names. Number 2 would be easy to implement but is likely to have false positives, eg. the number 88 has significance in Chinese numerology. Number 3 would also be hard to implement, interpreting clothing from a picture would most likely require some level of machine learning.
> 
> I would look into [soupcan](https://github.com/bethylamine/soupcan) for the first two.

Closing under these grounds.
