### ISSUE TITLE
Feature Request: Option to not block Blue users followed by accounts I'm following

### ISSUE THREAD

**Issue by lenethx** [kheina-com/Blue-Blocker#236]
There's a lot of artists and people in general that have blue and I'd like to avoid blocking. Given how many people the average user follows, I think it's reasonable to assume a good portion of these would be covered by just not blocking follows of followers. 
Ideally this would also unblock users blocked by the extension who are already followed by people i follow in the future.

**Comment by cooljeanius** [comment]
This is a dup of issue #122

**Comment by cooljeanius** [comment]
hm, the button for adding labels to issues appears to have disappeared on me, but anyways this ought to be given the "duplicate" label...

**Comment by cooljeanius** [comment]
...wait seriously, my adblocker was hiding it?! That's annoying...
