### ISSUE TITLE
Add user feedback for twitter users being blocked

### ISSUE THREAD

**Issue by Michael-Gibbons** [kheina-com/Blue-Blocker#25]
Thank you so much for this extension. I think part of the reason why the google reviews are a bit low is due to the lack of user feedback.

I think if we displayed the block queue in the popup it would be more apparent so people don't have to open dev tools to see the logs.

![image](https://user-images.githubusercontent.com/13829417/235278411-4217cbc1-50d5-4c7d-be18-e4183c676f54.png)

**Comment by DanielleMiu** [comment]
I think it's because the addon didn't work for a long time. honestly it's mostly thanks to https://github.com/kheina-com/Blue-Blocker/pull/10 that I picked up interest in it again.
on the topic, though. I think it would be fun to add an adblocker-style counter to the icon button 
![image](https://user-images.githubusercontent.com/29378233/235284516-5064417c-0196-447d-a09b-76b1c8224d2d.png)

**Comment by DanielleMiu** [comment]
unfortunately it seems like setting badge text is impossible from `content_scripts`, so the above will be on hold indefinitely if/when the script can be reworked into a `service_worker`

**Comment by DanielleMiu** [comment]
alright, well the disappointing update is that it's not possible to bind to requests in service workers the way we do with the `inject.js` script in `service_worker` scripts. so, it seems this might not be possible unless there's some sort of way to trigger a service worker binding from a content script

**Comment by Michael-Gibbons** [comment]
@DanielleMiu is there any reason we couldn't store the block queue in local storage, then in the popup print some text like "X number of people in queue to be blocked" then maybe store an int in local storage that gets incremented every time someone has been blocked to display "X number of people blocked"
![image](https://user-images.githubusercontent.com/13829417/235322979-2284588e-12af-431e-99e2-48c5baa9f66f.png)

**Comment by DanielleMiu** [comment]
I'm actually working on that right now. currently testing both platforms

**Comment by DanielleMiu** [comment]
I added my ideas to https://github.com/kheina-com/Blue-Blocker/pull/30. I don't like that the menu is updated through polling of the local storage. I think it should be possible through some sort of event or network or something, but I don't think my js/addon knowledge is good enough to figure how to do it currently

**Comment by DanielleMiu** [comment]
just discovered [browser.storage.local.onChanged](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea/onChanged), updating pr

**Comment by DanielleMiu** [comment]
I know I closed this already, but I realized we could use the same `onChanged` interface to get badge counter working in the service worker. so I have that working on chrome currently in https://github.com/kheina-com/Blue-Blocker/pull/27
