### ISSUE TITLE
Release workflow failure

### ISSUE THREAD

**Issue by rougetimelord** [kheina-com/Blue-Blocker#251]
The new workflow trips up when it tries to cat the manifest.json to match version strings, because `build/manifest.json` does not exist!

**Comment by rougetimelord** [comment]
I don't know a whole lot about actions, but shouldn't there be a job before the release jobs that runs `npm run build`?

**Comment by kheina** [comment]
oh yeah

**Comment by kheina** [comment]
https://github.com/kheina-com/Blue-Blocker/pull/252
