### ISSUE TITLE
chrome release workflow still not working

### ISSUE THREAD

**Issue by kheina** [kheina-com/Blue-Blocker#254]
https://github.com/kheina-com/Blue-Blocker/actions/runs/8695104297

seems like the firefox one worked ok, we'll see if they approve it since it's not possible to include source code in the reviewer notes, it might be worthwhile to work on the yml more to be able to link directly to the release tag. idk if a bunch of the things work since the workflow itself said it didn't recognize some of the things I used, but the publish did work
![image](https://github.com/kheina-com/Blue-Blocker/assets/29378233/0c570009-321f-44d2-afd1-fdccca6603a9)

as for chrome.... yeah google's auth system sucks idk what to do about that yet

**Comment by kheina** [comment]
https://github.com/kheina-com/Blue-Blocker/pull/255 might fix

**Comment by rougetimelord** [comment]
Did #256 work out?

**Comment by kheina** [comment]
oh yeah, please see https://github.com/kheina-com/Blue-Blocker/discussions/258
