### ISSUE TITLE
Add foldable sections to the popup settings

### ISSUE THREAD

**Issue by MaxIsJoe** [kheina-com/Blue-Blocker#279]
As the extension gets more feature rich, and its use case expands from a simple blue-checkmark blocker to a more general self-moderation tool, a lot of the settings we offer might start cluttering up the popup, especially if some of these settings rely on other ones being enabled.

The solution is to divide all settings into clearly labeled sections that can be hidden when the user doesn't want to see them. Each section will group a bunch of settings together based on what their intended functionality. 
For example, all settings that are purely cosmetic can be added into an "Appearance" section, which lets you control things like the popup timer and where the popup shows up. 

This will also help us future-proof the extension for whenever we add more integrations or other requested features into the extension, and should help us more easily organize where each setting should be placed.

The current sections I suggest are:
- General settings (mute instead of block, block people I follow, etc)
- Verified Accounts (block/skip verified accounts, skip users with a specific amount of followers, etc)
- Self-mod (#275, block nft users, etc)
- Integrations (soupcan, oldtwitter, etc)
- Appearance (popup timer, popup location, etc)

**Comment by rougetimelord** [comment]
Do you want to be assigned this issue?

**Comment by MaxIsJoe** [comment]
I have exams in a week or so, so I won't be able to work on this for at least a month. Please don't assign me for the time being, so if anyone else wants to work on this, they can be assigned to it instead.

**Comment by kheina** [comment]
this is what the tabs were kind of intended to be

**Comment by kheina** [comment]
I'll prolly pick this up

**Comment by rougetimelord** [comment]
> this is what the tabs were kind of intended to be

we gotta stop adding features 😭😭😭

**Comment by rougetimelord** [comment]
@MaxIsJoe check out v0.4.3 :)
