### ISSUE TITLE
due to twitter's forced redirect from twitter.com to x.com, the extension no longer works

### ISSUE THREAD

**Issue by Loch32** [kheina-com/Blue-Blocker#280]
as described above. twitter.com is now force redirected to x.com and attempting to access twitter.com once it has changed for you will show the "browser not supported" page. this braks the extension as it is now unable to read data from x.com as it is looking for twitter.com

https://github.com/kheina-com/Blue-Blocker/assets/140365955/5cb13be9-721c-4e9c-939a-f57a45d70a61

**Comment by rougetimelord** [comment]
On my end going to x.com still redirects to twitter.com, so maybe this is a rolling change on their end? Pretty easy fix to add x.com to the permissions.

This isn't super neccessary, but could you open the network tab of your browser's devtools, filter for JSON, and tell me the URL for the first request? (Like `https://twitter.com/i/api/1.1/jot/client_event.json`)

**Comment by Baramanga** [comment]
Yeah uh it's all x.com now. The and the Blue Blocker is now no longer picking up accounts.

**Comment by cooljeanius** [comment]
> Yeah uh it's all x.com now. The and the Blue Blocker is now no longer picking up accounts.

Yeah I got hit by this last night too

**Comment by bb115** [comment]
yeah mine stopped working as well hopefully you all working on a patch great extension btw

**Comment by Kannamoris** [comment]
Can confirm that this is indeed the case.

**Comment by cooljeanius** [comment]
This ought to be fixed once #267 is merged and 0.4.2 is released

**Comment by namkwal** [comment]
confirming this as well... ive been trying to add x.com to permission but brave's ui is insanely wacky

**Comment by WineKitty** [comment]
How do i make it work again i have 0 coding knowledge but hate browsing twitter without this add on

**Comment by rougetimelord** [comment]
Popping in again to say that the 0.4.2 branch does work, we're currently testing it to make sure we don't have a bunch of bugs in the public version. If you want to help test it, please comment any issues you run into on the pull request (#267)

**Comment by alcayaga** [comment]
As a workaround you can access the old domain using the variable mx in the url:

`https://twitter.com/home?mx=1`

**Comment by Baramanga** [comment]
> Popping in again to say that the 0.4.2 branch does work, we're currently testing it to make sure we don't have a bunch of bugs in the public version. If you want to help test it, please comment any issues you run into on the pull request (#267)

Hey uh, maybe I'm just being obtuse but how do I install the extension on Firefox before it's officially "released" on the store front? The version I have rn is the same as on the store front, which is 0.3.5. Is there like a folder, with the zip file I can download the extension with the firefox signature?

**Comment by kheina** [comment]
> > Popping in again to say that the 0.4.2 branch does work, we're currently testing it to make sure we don't have a bunch of bugs in the public version. If you want to help test it, please comment any issues you run into on the pull request (#267)
> 
> Hey uh, maybe I'm just being obtuse but how do I install the extension on Firefox before it's officially "released" on the store front? The version I have rn is the same as on the store front, which is 0.3.5. Is there like a folder, with the zip file I can download the extension with the firefox signature?

I just added binaries to the release https://github.com/kheina-com/Blue-Blocker/releases/tag/v0.4.2

**Comment by kheina** [comment]
though, for now, I would recommend @alcayaga's solution

> As a workaround you can access the old domain using the variable mx in the url:
>
> [`https://twitter.com/home?mx=1`](https://twitter.com/home?mx=1)

the next version should be available soon, it's just waiting on firefox to approve and it will go out automatically

![image](https://github.com/kheina-com/Blue-Blocker/assets/29378233/97bbcc0e-385c-4540-9a8a-8ce0920d9409)
