### ISSUE TITLE
No blue checks queued or blocked since twitter has forced the url change to x.com

### ISSUE THREAD

**Issue by gbootsma** [kheina-com/Blue-Blocker#288]
Since twitter has moved over to x.com, no new users have been blocked or queued - is the change to x.com causing an issue?

**Comment by gbootsma** [comment]
Some extra information: I use blueblocker in firefox on two windows PCs, and the issue exists at both of them

**Comment by cooljeanius** [comment]
Make sure you've updated to [v0.4.2](https://github.com/kheina-com/Blue-Blocker/releases/tag/v0.4.2) if you haven't already 
(My version of Firefox still has me on v0.3.5 for some reason, so you may need to force the update)

**Comment by gbootsma** [comment]
That explains it - my version was still 0.3.5 - though the mozilla add-ons page is also still on that version, which may be why it hasn't updated

 https://addons.mozilla.org/en-GB/firefox/addon/blue-blocker/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

**Comment by cooljeanius** [comment]
See discussion in #258 about why the Firefox version might still be behind

**Comment by Baramanga** [comment]
So uh, how long does it usually take for this to be updated? Also the zip file give me signature error when I try to install it 😭

**Comment by kheina** [comment]
> So uh, how long does it usually take for this to be updated? Also the zip file give me signature error when I try to install it 😭

unfortunately, it was rejected, check this thread for more info https://github.com/kheina-com/Blue-Blocker/discussions/294
