### ISSUE TITLE
does not work after twitter changed domain to X

### ISSUE THREAD

**Issue by rueqen** [kheina-com/Blue-Blocker#291]
i'm using firefox (126.0) and the addon version is on 0.3.5
it was working fine until twitter changed its domain and now blocking does not work, even after turning off "pause user collection"
when i browse around it does not seem to collect blue checks into queue either

**Comment by kheina** [comment]
https://github.com/kheina-com/Blue-Blocker/issues/288#issuecomment-2127394093
