### ISSUE TITLE
Switch to x.com domain

### ISSUE THREAD

**Issue by Jeshibu** [kheina-com/Blue-Blocker#297]
Hey there, it seems like twitter.com unfortunately finally redirects to x.com now. This renders this extension non-functional I think, because it has permission to use twitter.com, not x.com.

**Comment by kheina** [comment]
https://github.com/kheina-com/Blue-Blocker/issues/280
https://github.com/kheina-com/Blue-Blocker/discussions/294

**Comment by Jeshibu** [comment]
Woops, didn't look in the closed issues. My bad. Would it be possible to add a one-click-installable firefox file to the latest release instead?
