### ISSUE TITLE
extension integration (soupcan) not working

### ISSUE THREAD

**Issue by fred-ronnoc** [kheina-com/Blue-Blocker#300]
I have no idea if its a blueblocker issue or a soupcan issue but the soupcan integration hasn't been working since the 0.4.2 update and i cant seem to find the problem anywhere

**Comment by cooljeanius** [comment]
Could you provide some additional details? How exactly is it failing to work?

**Comment by fred-ronnoc** [comment]
for whatever reason, blueblocker does seem to be blocking anyone marked as transphobic on soupcan despite having the integration present and the option enabled. I'm not sure its just user error or if its a bug in the way integrations were coded.

**Comment by cooljeanius** [comment]
- what version of soupcan?
- what browser?
- any other extensions installed that might be interfering?
- any diagnostic output from logs or anything?

**Comment by fred-ronnoc** [comment]
1. Soupcan Version 0.22.6
2. operagx browser
3. I don't think any of my other extensions are interfering
4. I'm sorry but I don't know how to check logs

**Comment by lovelydumpling** [comment]
Having the same problem on firefox

**Comment by rougetimelord** [comment]
I pushed a change to soupcan to get them onto the new integration system, but never got around to making changes on our side to move them over.

**Comment by rougetimelord** [comment]
Sorry! Been super busy, I won't be able to get around to this for probably a month or two at best. Should just be deleting special handling for soupcan, and adding logic to gracefully migrate the `config.soupcanIntegration` key to the new integration system

**Comment by rougetimelord** [comment]
See: https://github.com/rougetimelord/Blue-Blocker/tree/soupcan-migration

**Comment by cooljeanius** [comment]
> See: [rougetimelord/Blue-Blocker@`soupcan-migration`](https://github.com/rougetimelord/Blue-Blocker/tree/soupcan-migration?rgh-link-date=2024-09-06T15%3A55%3A28Z)

...which is PR #336 now.
