### ISSUE TITLE
Extension not working at all

### ISSUE THREAD

**Issue by PancakeIdentity** [kheina-com/Blue-Blocker#304]
Hey all, I hope this report isn't too vague, I will try to give as many details as possible but I don't feel there's much to work with. But - the extension is not working at all. Users are not added to the queue. The only boxes I have checked in the settings menu are to show the pop up, and to block people who promote tweets and NFT avatars. (Most importantly, the box that pauses user collection is not checked.) I am on Firefox and am using no extensions that impact Twitter other than an adblocker. Both Firefox and extension are fully updated. (127.0 and 0.3.5 respectively). The Firefox log for the extension shows nothing other than an error saying "soupcan response for @elonmusk: Error: Could not establish connection. Receiving end does not exist." whenever the extension menu is opened.

Please let me know if any more information is needed and how I can give it. Thank you!

**Comment by Brasan** [comment]
I'm in the same boat. According to #280 it broke when twitter started redirecting to x.com. A fixed version is out, but is still waiting for Mozilla approval to be pushed to firefox users, so we can't do much but wait.
