### ISSUE TITLE
Firefox version is out of date, and no longer works.

### ISSUE THREAD

**Issue by MaxIsJoe** [kheina-com/Blue-Blocker#309]
The firefox version is stuck on 3.5.0, which is outdated and no longer works.

I assume this might be related to #270 ? Regardless, It's been an issue that has gone on for a very long while now.

**Comment by kheina** [comment]
https://github.com/kheina-com/Blue-Blocker/issues/280 https://github.com/kheina-com/Blue-Blocker/discussions/294

**Comment by WinterFloof** [comment]
Do we have any idea when 0.4.2 will be verified for Firefox users?

**Comment by kheina** [comment]
honestly just assume that 0.4.2 isn't happening on Firefox. we'll address their complaints in 0.4.3

**Comment by cooljeanius** [comment]
> honestly just assume that 0.4.2 isn't happening on Firefox. we'll address their complaints in 0.4.3

(the PR for which is #312, for reference)
