### ISSUE TITLE
blueblocker ignoring follower limit and blocking everyone

### ISSUE THREAD

**Issue by fred-ronnoc** [kheina-com/Blue-Blocker#310]
blueblocker is currently blocking anyone with twitter blue, including people with over 1 million followers even though it should be ignoring them, it blocked the account @hamster_kombat for "using Twitter Blue features" despite the fact that they have 11m followers

**Comment by kheina** [comment]
I'll look after work

**Comment by rougetimelord** [comment]
This is expected behavior.

The "block users that use blue features" option overrides any options that would otherwise skip a user. The popup includes a warning when the option is selected.

**Comment by fred-ronnoc** [comment]
oh, i thought that option would ignore anyone with over the specified amount of followers
