### ISSUE TITLE
Blue can be gifted now

### ISSUE THREAD

**Issue by cooljeanius** [kheina-com/Blue-Blocker#311]
See: https://x.com/aluladotme/status/1811774912425578696
If there's a way to tell whether someone received Blue as a gift or not, I personally would like to be able to tell BlueBlocker to be able to skip people who received it as a gift (unless they then go and actually use its features)

**Comment by rougetimelord** [comment]
Closing, I don't think we're going to get to see whether blue was gifted or not :(
