### ISSUE TITLE
Extension no longer working

### ISSUE THREAD

**Issue by GMLW** [kheina-com/Blue-Blocker#316]
I don't know what else to mention besides the fact that I use Firefox. The extension simply doesn't work anymore and it hasn't for at least a week at this point, maybe two weeks. I haven't changed any settings recently.

**Comment by glowstickblood** [comment]
Also on Firefox. Mine hasn't worked since the domain change from twitter to x, so I've been kind of assuming that's the problem.

**Comment by cooljeanius** [comment]
dup; see #280 and #294
