### ISSUE TITLE
Not working since redirection forces to display "x.com"

### ISSUE THREAD

**Issue by indirectvomitorium** [kheina-com/Blue-Blocker#318]
Hi !
I use the extension with Firefox, worked fine until few days ago.

Context : I also use this extension https://github.com/insin/control-panel-for-twitter/
Control panel allowed me to keep the URL in the format "twitter.com/xxxx" and not "x.com/xxxx"
As long as the URL was "Twitter", Blue Blocker worked just fine.

But few days ago, the change in the URL wasn't happening anymore, and I can't block/mute annoying peoples.

Hope this helps, sorry for my bad english.
Don't hesitate to contact me for any more infos.

👋👋👋

**Comment by cooljeanius** [comment]
Duplicate; see #280 and #294 for more info.
