### ISSUE TITLE
Release for regular Firefox users

### ISSUE THREAD

**Issue by Tosh0kan** [kheina-com/Blue-Blocker#329]
Do you intend on ever updating the mainline version, ie, the version we get from https://addons.mozilla.org?

**Comment by kheina** [comment]
please see https://github.com/kheina-com/Blue-Blocker/discussions/294, https://github.com/kheina-com/Blue-Blocker/discussions/321, and https://github.com/kheina-com/Blue-Blocker/discussions/327
