### ISSUE TITLE
Firefox extension very out of date

### ISSUE THREAD

**Issue by typecasto** [kheina-com/Blue-Blocker#330]
Has the firefox extension been abandoned or something? It's been broken for several months now, and doesn't seem to be receiving any of the new updates, it's still on 0.3.5.

**Comment by kheina** [comment]
please see https://github.com/kheina-com/Blue-Blocker/discussions/327, https://github.com/kheina-com/Blue-Blocker/discussions/321, and https://github.com/kheina-com/Blue-Blocker/discussions/294
