### ISSUE TITLE
Firefox does not have access to "x.com"

### ISSUE THREAD

**Issue by T-Espino** [kheina-com/Blue-Blocker#331]
On firefox the extension does not have access to "x.com" it only asks for permissions for twitter.com which means it doesn't work at all on firefox.

**Comment by kheina** [comment]
please see https://github.com/kheina-com/Blue-Blocker/discussions/327, https://github.com/kheina-com/Blue-Blocker/discussions/321, and https://github.com/kheina-com/Blue-Blocker/discussions/294
