### ISSUE TITLE
Firefox plugin broken on x.com domain due to outdated release currently published.

### ISSUE THREAD

**Issue by distransient** [kheina-com/Blue-Blocker#332]
The Firefox addon needs an update. It's currently at version `0.3.5` which is broken since the `twitter.com` domain's been fully redirected to `x.com`, the issue #280 fixed in #282 and released in `0.4.2`. Can confirm on Firefox `129.0.2` that manually using at least the `0.4.2` release resolves this issue, so the addon on the Firefox store just needs bumped.

**Comment by gbootsma** [comment]
See #294 #321 and #327, there have been issues getting the newer versions accepted on the firefox add-on store - hopefully they'll be able to sort that soon

**Comment by cooljeanius** [comment]
> See #294 #321 and #327, there have been issues getting the newer versions accepted on the firefox add-on store - hopefully they'll be able to sort that soon

Yeah, if you know TypeScript and/or the NPM ecosystem at all, help figuring it out would be appreciated!

**Comment by distransient** [comment]
I have a bit of experience with ts but not uploading firefox addons, I will read up at least to see if there's anything I can do to help. Thank you
