### ISSUE TITLE
Firefox add-on not working on x.com

### ISSUE THREAD

**Issue by xkevinx** [kheina-com/Blue-Blocker#340]
Hi!

First off, thanks for your work!

I noticed that recently the Firefox add-on was not working anymore. I'm not sure but I think it is because the extension has only the permissions on `twitter.com` and not `x.com`, and now twitter automatically redirects to x.com so there's no way to use the original address.

I don't think there's a way to add permissions to another website manually on my side, right?

**Comment by cooljeanius** [comment]
Yeah this is unfortunately a known issue; see discussion in #294, #321 and #327. If there's anything you could do to help us get Mozilla to approve our updates, it'd be appreciated!

**Comment by xkevinx** [comment]
ah sorry for the duplicate, I did research in the issues but not in the discussions! I'll take a look at the discussions but I doubt there's anything I could do unfortunately.
