### ISSUE TITLE
Import a block list 

### ISSUE THREAD

**Issue by Skillou** [kheina-com/Blue-Blocker#341]
Add the feature : Import block list to block every person on the list by user Id or twitter name please : 
Example of my json of blocked user
    {
      "id": "1778338116564078592",
      "name": "babouche 2",
      "username": "megababouche2"
    }

**Comment by rougetimelord** [comment]
Feature already exists, on the queue page you can import block lists in CSV or JSON format.
![image](https://github.com/user-attachments/assets/3cbcf76e-52b8-47cb-bdd6-21e9a19d3a40)
![image](https://github.com/user-attachments/assets/2b422c1d-4e3f-46ca-8385-e619b75e7703)
![image](https://github.com/user-attachments/assets/0943230e-81da-48ef-8898-e63eb84b4324)

**Comment by cooljeanius** [comment]
> Feature already exists, on the queue page you can import block lists in CSV or JSON format.

So wait, does this mean that we can close #226 now, too, then?

**Comment by rougetimelord** [comment]
> > Feature already exists, on the queue page you can import block lists in CSV or JSON format.
> 
> So wait, does this mean that we can close #226 now, too, then?

No, #226 also includes exporting block lists
