### ISSUE TITLE
Firefox usage on x.com

### ISSUE THREAD

**Issue by willthamic** [kheina-com/Blue-Blocker#343]
<img width="1221" alt="Screenshot 2024-09-23 at 9 53 07 PM" src="https://github.com/user-attachments/assets/9abd9818-e9c9-4d6a-9c25-658a4503464f">
Twitter now seems to be forcing URL redirects to x.com from twitter.com (at least on my account). This seems to prevent the extension working in firefox for me. Checking app settings both in the app and in firefox, I can't find a way to enable permissions for x.com, just twitter.com.

**Comment by cooljeanius** [comment]
Yeah this is unfortunately a known issue; see discussion in #294, #321 and #327. If there's anything you could do to help us get Mozilla to approve our updates, it'd be appreciated!
