### ISSUE TITLE
[bug] release workflow zips firefox too early

### ISSUE THREAD

**Issue by rougetimelord** [kheina-com/Blue-Blocker#360]
**Describe the bug**
The release workflow for Firefox tries to zip the extension before node is set up and the extension is built

**To Reproduce**
N/A

**Expected behavior**
Node is set up and the build command is run before the extension is zipped.

**Screenshots and console logs**
```
Run SOURCE_FILENAME="blue-blocker-source-$(make version).zip"
cat: build/manifest.json: No such file or directory
makefile:[9](https://github.com/kheina-com/Blue-Blocker/actions/runs/11312095101/job/31459098520#step:3:10): *** Extension version mismatch. manifest: , package.json: "0.4.10".  Stop.
Error: Process completed with exit code 2.
```

**Please fill in the following information:**
N/A

**Additional context**
I'm too sleepy to fix this rn, ping me tomorrow or PR it. Should be pretty easy to just move the zipping step down.

**Comment by cooljeanius** [comment]
> **Additional context** I'm too sleepy to fix this rn, ping me tomorrow or PR it.

I've assigned you for now.

**Comment by rougetimelord** [comment]
Oops, misread, it's failing to zip up the source code. Same solution though
