### ISSUE TITLE
Content script is blocked from loading in Chrome

### ISSUE THREAD

**Issue by Lumpef** [kheina-com/Blue-Blocker#365]
Upon accessing X.com, Chrome refuses to load a script that BlueBlocker uses.
Because of this, accounts are not being blocked, nor added to the queue.
I believe the extension was working normally for me as of yesterday.

**Console Log:**
[x.com-1729112663037.log](https://github.com/user-attachments/files/17402833/x.com-1729112663037.log)

**Console Screenshot:**
![console_screencap](https://github.com/user-attachments/assets/1e471aba-df4f-47f1-b0d6-94d1b91f376b)

(Please excuse my other extension, 'BlueLiteBlocker', loading successfully in the console right before the error; the names being so similar confused me for a sec)

**My set up:**
Chrome version: 130.0.6723.58
BlueBlocker version: 0.4.10

I also have the following extensions which could modify Twitter:
'BlueLiteBlocker'
'Control Panel for Twitter'
'uBlock Origin Dev Build'
'Eight Dollars'
'Stylus'
'Tampermonkey'

I'm happy to help diagnose the issue in any way I can! Thank you!

**Comment by rougetimelord** [comment]
That chrome-extension URL looks really weird! Something is going wrong on Chrome's end if it's returning that from `Chrome.runtime.getURL(...)`

Can you navigate to [chrome://extensions/](chrome://extensions/) and add a screenshot of the Blue Blocker tile on there? Should look like this:
![image](https://github.com/user-attachments/assets/8de90b34-d86a-4ed6-ab32-37a9b9de1aea)

**Comment by Lumpef** [comment]
Sure thing, here you go!

![BB](https://github.com/user-attachments/assets/45361212-d9f6-4b4c-95c4-dce92acf3ecc)

**Comment by rougetimelord** [comment]
Alright can replicate now. Weird, pretty sure this a Chrome change

**Comment by rougetimelord** [comment]
Found documentation for the change: https://groups.google.com/a/chromium.org/g/chromium-extensions/c/Nr3QNKFv74c/m/PYLvA7dOAAAJ?pli=1

**Comment by rougetimelord** [comment]
Alright, definitely a Chrome breaking change :)))) https://issues.chromium.org/issues/363027634

**Comment by rougetimelord** [comment]
Fix complete, going to publish the update today and hopefully have it up sometime in the next few days
