### ISSUE TITLE
[bug] Firefox release failure v0.4.11

### ISSUE THREAD

**Issue by rougetimelord** [kheina-com/Blue-Blocker#367]
**Describe the bug**
The Firefox release workflow failed to zip the source code

**To Reproduce**
N/A

**Expected behavior**
Source code is zipped correctly

**Screenshots and console logs**
```
zip warning:   first full name: ././.editorconfig
                      second full name: ./.editorconfig
                     name in zip file repeated: .editorconfig

zip error: Invalid command arguments (cannot repeat names in zip file)
```

**Please fill in the following information:**
N/A

**Additional context**
N/A

**Comment by cooljeanius** [comment]
hm, I wonder if this has to do with changing around the order of things in the workflow recently?

**Comment by rougetimelord** [comment]
> hm, I wonder if this has to do with changing around the order of things in the workflow recently?

I don't think so? The problem seems to be that we were running `zip "./*" "././*"` which caught the editor config file twice for some reason?

**Comment by cooljeanius** [comment]
> > hm, I wonder if this has to do with changing around the order of things in the workflow recently?
> 
> I don't think so? The problem seems to be that we were running `zip "./*" "././*"` which caught the editor config file twice for some reason?

OK well as long as #368 fixes it, whatever...

**Comment by rougetimelord** [comment]
The release workflow worked! Yay!!
