### ISSUE TITLE
[bug] `npm install` results in `SyntaxError: Unexpected token {` 

### ISSUE THREAD

**Issue by Poddster** [kheina-com/Blue-Blocker#369]
# **Describe the bug**
I ran `npm install` as instucted in the README and it didn't work

# **To Reproduce**
    npm -v
    jq --version
    git clone https://github.com/kheina-com/Blue-Blocker.git
    cd Blue-Blocker
    npm install

# **Expected behavior**
It didn't work. I don't know anything about npm, but it looks like this is the first error:

    > node-jq@6.0.1 preinstall /home/pod/src/temp/Blue-Blocker/node_modules/node-jq
    > npm run install-binary

    > node-jq@6.0.1 install-binary /home/pod/src/temp/Blue-Blocker/node_modules/node-jq
    > node scripts/install-binary.mjs

    /home/pod/src/temp/Blue-Blocker/node_modules/node-jq/scripts/install-binary.mjs:5
    import { spawn } from 'node:child_process'
           ^

    SyntaxError: Unexpected token {
        at Module._compile (internal/modules/cjs/loader.js:723:23)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
        at Module.load (internal/modules/cjs/loader.js:653:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
        at Function.Module._load (internal/modules/cjs/loader.js:585:3)
        at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
        at startup (internal/bootstrap/node.js:283:19)
        at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! node-jq@6.0.1 install-binary: `node scripts/install-binary.mjs`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the node-jq@6.0.1 install-binary script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

# **Screenshots and console logs**

    pod@pod-PC2:~/src/temp$ cat build_blue_blocker.sh
    #!/bin/bash
    set -xe

    npm -v
    jq --version
    git clone https://github.com/kheina-com/Blue-Blocker.git
    cd Blue-Blocker
    npm install
    npm run dev
    npm run build
    make firefox

    pod@pod-PC2:~/src/temp$ ./build_blue_blocker.sh
    + npm -v
    6.14.4
    + jq --version
    jq-1.6
    + git clone https://github.com/kheina-com/Blue-Blocker.git
    Cloning into 'Blue-Blocker'...
    remote: Enumerating objects: 1124, done.
    remote: Counting objects: 100% (677/677), done.
    remote: Compressing objects: 100% (393/393), done.
    remote: Total 1124 (delta 464), reused 367 (delta 283), pack-reused 447 (from 1)
    Receiving objects: 100% (1124/1124), 900.14 KiB | 2.76 MiB/s, done.
    Resolving deltas: 100% (645/645), done.
    + cd Blue-Blocker
    + npm install
    npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@3. I'll try to do my best with it!
    npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
    npm WARN deprecated q@1.5.1: You or someone you depend on is using Q, the JavaScript Promise library that gave JavaScript developers strong feelings about promises. They can almost certainly migrate to the native JavaScript promise now. Thank you literally everyone for joining me in this bet against the odds. Be excellent to each other.
    npm WARN deprecated
    npm WARN deprecated (For a CapTP with native promises, see @endo/eventual-send and @endo/captp)

    > node-jq@6.0.1 preinstall /home/pod/src/temp/Blue-Blocker/node_modules/node-jq
    > npm run install-binary

    > node-jq@6.0.1 install-binary /home/pod/src/temp/Blue-Blocker/node_modules/node-jq
    > node scripts/install-binary.mjs

    /home/pod/src/temp/Blue-Blocker/node_modules/node-jq/scripts/install-binary.mjs:5
    import { spawn } from 'node:child_process'
           ^

    SyntaxError: Unexpected token {
        at Module._compile (internal/modules/cjs/loader.js:723:23)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
        at Module.load (internal/modules/cjs/loader.js:653:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
        at Function.Module._load (internal/modules/cjs/loader.js:585:3)
        at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
        at startup (internal/bootstrap/node.js:283:19)
        at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! node-jq@6.0.1 install-binary: `node scripts/install-binary.mjs`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the node-jq@6.0.1 install-binary script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    npm WARN Local package.json exists, but node_modules missing, did you mean to install?

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/pod/.npm/_logs/2024-10-25T09_57_04_134Z-debug.log
    npm WARN notsup Unsupported engine for node-jq@6.0.1: wanted: {"node":">= 18"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: node-jq@6.0.1
    npm WARN notsup Unsupported engine for typescript@5.6.3: wanted: {"node":">=14.17"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: typescript@5.6.3
    npm WARN notsup Unsupported engine for vite@3.2.11: wanted: {"node":"^14.18.0 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: vite@3.2.11
    npm WARN notsup Unsupported engine for html-minifier-terser@7.2.0: wanted: {"node":"^14.13.1 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: html-minifier-terser@7.2.0
    npm WARN notsup Unsupported engine for cheerio@1.0.0: wanted: {"node":">=18.17"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: cheerio@1.0.0
    npm WARN notsup Unsupported engine for fs-extra@10.1.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: fs-extra@10.1.0
    npm WARN notsup Unsupported engine for magic-string@0.26.7: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: magic-string@0.26.7
    npm WARN notsup Unsupported engine for undici@6.20.1: wanted: {"node":">=18.17"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: undici@6.20.1
    npm WARN notsup Unsupported engine for whatwg-mimetype@4.0.0: wanted: {"node":">=18"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: whatwg-mimetype@4.0.0
    npm WARN notsup Unsupported engine for whatwg-encoding@3.1.1: wanted: {"node":">=18"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: whatwg-encoding@3.1.1
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/@crxjs/vite-plugin/node_modules/rollup/node_modules/fsevents):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
    npm WARN notsup Unsupported engine for commander@10.0.1: wanted: {"node":">=14"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: commander@10.0.1
    npm WARN notsup Unsupported engine for tar@7.4.3: wanted: {"node":">=18"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: tar@7.4.3
    npm WARN notsup Unsupported engine for tempy@3.1.0: wanted: {"node":">=14.16"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: tempy@3.1.0
    npm WARN notsup Unsupported engine for @isaacs/fs-minipass@4.0.1: wanted: {"node":">=18.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: @isaacs/fs-minipass@4.0.1
    npm WARN notsup Unsupported engine for chownr@3.0.0: wanted: {"node":">=18"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: chownr@3.0.0
    npm WARN notsup Unsupported engine for yallist@5.0.0: wanted: {"node":">=18"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: yallist@5.0.0
    npm WARN notsup Unsupported engine for minizlib@3.0.1: wanted: {"node":">= 18"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: minizlib@3.0.1
    npm WARN notsup Unsupported engine for minipass@7.1.2: wanted: {"node":">=16 || 14 >=14.17"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: minipass@7.1.2
    npm WARN notsup Unsupported engine for minimatch@9.0.5: wanted: {"node":">=16 || 14 >=14.17"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: minimatch@9.0.5
    npm WARN notsup Unsupported engine for path-scurry@1.11.1: wanted: {"node":">=16 || 14 >=14.18"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: path-scurry@1.11.1
    npm WARN notsup Unsupported engine for foreground-child@3.3.0: wanted: {"node":">=14"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: foreground-child@3.3.0
    npm WARN notsup Unsupported engine for signal-exit@4.1.0: wanted: {"node":">=14"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: signal-exit@4.1.0
    npm WARN notsup Unsupported engine for @isaacs/cliui@8.0.2: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: @isaacs/cliui@8.0.2
    npm WARN notsup Unsupported engine for @pkgjs/parseargs@0.11.0: wanted: {"node":">=14"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: @pkgjs/parseargs@0.11.0
    npm WARN notsup Unsupported engine for string-width@5.1.2: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: string-width@5.1.2
    npm WARN notsup Unsupported engine for wrap-ansi@8.1.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: wrap-ansi@8.1.0
    npm WARN notsup Unsupported engine for strip-ansi@7.1.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: strip-ansi@7.1.0
    npm WARN notsup Unsupported engine for ansi-regex@6.1.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: ansi-regex@6.1.0
    npm WARN notsup Unsupported engine for ansi-styles@6.2.1: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: ansi-styles@6.2.1
    npm WARN notsup Unsupported engine for is-stream@3.0.0: wanted: {"node":"^12.20.0 || ^14.13.1 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: is-stream@3.0.0
    npm WARN notsup Unsupported engine for temp-dir@3.0.0: wanted: {"node":">=14.16"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: temp-dir@3.0.0
    npm WARN notsup Unsupported engine for type-fest@2.19.0: wanted: {"node":">=12.20"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: type-fest@2.19.0
    npm WARN notsup Unsupported engine for unique-string@3.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: unique-string@3.0.0
    npm WARN notsup Unsupported engine for crypto-random-string@4.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: crypto-random-string@4.0.0
    npm WARN notsup Unsupported engine for esbuild@0.15.18: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: esbuild@0.15.18
    npm WARN notsup Unsupported engine for esbuild-linux-32@0.15.18: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: esbuild-linux-32@0.15.18
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-32@0.15.18 (node_modules/esbuild/node_modules/esbuild-linux-32):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-32@0.15.18: wanted {"os":"linux","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
    npm WARN notsup Unsupported engine for esbuild-sunos-64@0.15.18: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: esbuild-sunos-64@0.15.18
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-sunos-64@0.15.18 (node_modules/esbuild/node_modules/esbuild-sunos-64):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-sunos-64@0.15.18: wanted {"os":"sunos","arch":"x64"} (current: {"os":"linux","arch":"x64"})
    npm WARN notsup Unsupported engine for esbuild-linux-64@0.15.18: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: esbuild-linux-64@0.15.18
    npm WARN notsup Unsupported engine for esbuild-darwin-64@0.15.18: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: esbuild-darwin-64@0.15.18
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-darwin-64@0.15.18 (node_modules/esbuild/node_modules/esbuild-darwin-64):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-darwin-64@0.15.18: wanted {"os":"darwin","arch":"x64"} (current: {"os":"linux","arch":"x64"})
    npm WARN notsup Unsupported engine for esbuild-linux-arm@0.15.18: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: esbuild-linux-arm@0.15.18
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-arm@0.15.18 (node_modules/esbuild/node_modules/esbuild-linux-arm):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-arm@0.15.18: wanted {"os":"linux","arch":"arm"} (current: {"os":"linux","arch":"x64"})
    npm WARN notsup Unsupported engine for esbuild-netbsd-64@0.15.18: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: esbuild-netbsd-64@0.15.18
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-netbsd-64@0.15.18 (node_modules/esbuild/node_modules/esbuild-netbsd-64):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-netbsd-64@0.15.18: wanted {"os":"netbsd","arch":"x64"} (current: {"os":"linux","arch":"x64"})
    npm WARN notsup Unsupported engine for esbuild-android-64@0.15.18: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: esbuild-android-64@0.15.18
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-android-64@0.15.18 (node_modules/esbuild/node_modules/esbuild-android-64):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-android-64@0.15.18: wanted {"os":"android","arch":"x64"} (current: {"os":"linux","arch":"x64"})
    npm WARN notsup Unsupported engine for esbuild-openbsd-64@0.15.18: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: esbuild-openbsd-64@0.15.18
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-openbsd-64@0.15.18 (node_modules/esbuild/node_modules/esbuild-openbsd-64):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-openbsd-64@0.15.18: wanted {"os":"openbsd","arch":"x64"} (current: {"os":"linux","arch":"x64"})
    npm WARN notsup Unsupported engine for esbuild-windows-32@0.15.18: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: esbuild-windows-32@0.15.18
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-windows-32@0.15.18 (node_modules/esbuild/node_modules/esbuild-windows-32):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-windows-32@0.15.18: wanted {"os":"win32","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
    npm WARN notsup Unsupported engine for esbuild-freebsd-64@0.15.18: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: esbuild-freebsd-64@0.15.18
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-freebsd-64@0.15.18 (node_modules/esbuild/node_modules/esbuild-freebsd-64):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-freebsd-64@0.15.18: wanted {"os":"freebsd","arch":"x64"} (current: {"os":"linux","arch":"x64"})
    npm WARN notsup Unsupported engine for esbuild-windows-64@0.15.18: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: esbuild-windows-64@0.15.18
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-windows-64@0.15.18 (node_modules/esbuild/node_modules/esbuild-windows-64):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-windows-64@0.15.18: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"x64"})
    npm WARN notsup Unsupported engine for esbuild-linux-arm64@0.15.18: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: esbuild-linux-arm64@0.15.18
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-arm64@0.15.18 (node_modules/esbuild/node_modules/esbuild-linux-arm64):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-arm64@0.15.18: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
    npm WARN notsup Unsupported engine for esbuild-linux-s390x@0.15.18: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: esbuild-linux-s390x@0.15.18
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-s390x@0.15.18 (node_modules/esbuild/node_modules/esbuild-linux-s390x):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-s390x@0.15.18: wanted {"os":"linux","arch":"s390x"} (current: {"os":"linux","arch":"x64"})
    npm WARN notsup Unsupported engine for @esbuild/android-arm@0.15.18: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: @esbuild/android-arm@0.15.18
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/android-arm@0.15.18 (node_modules/esbuild/node_modules/@esbuild/android-arm):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/android-arm@0.15.18: wanted {"os":"android","arch":"arm"} (current: {"os":"linux","arch":"x64"})
    npm WARN notsup Unsupported engine for esbuild-darwin-arm64@0.15.18: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: esbuild-darwin-arm64@0.15.18
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-darwin-arm64@0.15.18 (node_modules/esbuild/node_modules/esbuild-darwin-arm64):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-darwin-arm64@0.15.18: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
    npm WARN notsup Unsupported engine for esbuild-android-arm64@0.15.18: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: esbuild-android-arm64@0.15.18
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-android-arm64@0.15.18 (node_modules/esbuild/node_modules/esbuild-android-arm64):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-android-arm64@0.15.18: wanted {"os":"android","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
    npm WARN notsup Unsupported engine for esbuild-linux-ppc64le@0.15.18: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: esbuild-linux-ppc64le@0.15.18
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-ppc64le@0.15.18 (node_modules/esbuild/node_modules/esbuild-linux-ppc64le):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-ppc64le@0.15.18: wanted {"os":"linux","arch":"ppc64"} (current: {"os":"linux","arch":"x64"})
    npm WARN notsup Unsupported engine for esbuild-freebsd-arm64@0.15.18: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: esbuild-freebsd-arm64@0.15.18
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-freebsd-arm64@0.15.18 (node_modules/esbuild/node_modules/esbuild-freebsd-arm64):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-freebsd-arm64@0.15.18: wanted {"os":"freebsd","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
    npm WARN notsup Unsupported engine for esbuild-linux-riscv64@0.15.18: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: esbuild-linux-riscv64@0.15.18
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-riscv64@0.15.18 (node_modules/esbuild/node_modules/esbuild-linux-riscv64):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-riscv64@0.15.18: wanted {"os":"linux","arch":"riscv64"} (current: {"os":"linux","arch":"x64"})
    npm WARN notsup Unsupported engine for esbuild-windows-arm64@0.15.18: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: esbuild-windows-arm64@0.15.18
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-windows-arm64@0.15.18 (node_modules/esbuild/node_modules/esbuild-windows-arm64):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-windows-arm64@0.15.18: wanted {"os":"win32","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
    npm WARN notsup Unsupported engine for @esbuild/linux-loong64@0.15.18: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: @esbuild/linux-loong64@0.15.18
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/linux-loong64@0.15.18 (node_modules/esbuild/node_modules/@esbuild/linux-loong64):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/linux-loong64@0.15.18: wanted {"os":"linux","arch":"loong64"} (current: {"os":"linux","arch":"x64"})
    npm WARN notsup Unsupported engine for esbuild-linux-mips64le@0.15.18: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
    npm WARN notsup Not compatible with your version of node/npm: esbuild-linux-mips64le@0.15.18
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-mips64le@0.15.18 (node_modules/esbuild/node_modules/esbuild-linux-mips64le):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-mips64le@0.15.18: wanted {"os":"linux","arch":"mips64el"} (current: {"os":"linux","arch":"x64"})
    npm WARN blue-blocker@0.4.11 No repository field.

    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! node-jq@6.0.1 preinstall: `npm run install-binary`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the node-jq@6.0.1 preinstall script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/pod/.npm/_logs/2024-10-25T09_57_04_282Z-debug.log
    pod@pod-PC2:~/src/temp$ vim /home/pod/.npm/_logs/2024-10-25T09_57_04_282Z-debug.log
    pod@pod-PC2:~/src/temp$ npm run install-binary
    npm ERR! code ENOENT
    npm ERR! syscall open
    npm ERR! path /home/pod/src/temp/package.json
    npm ERR! errno -2
    npm ERR! enoent ENOENT: no such file or directory, open '/home/pod/src/temp/package.json'
    npm ERR! enoent This is related to npm not being able to find a file.
    npm ERR! enoent

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/pod/.npm/_logs/2024-10-25T09_57_56_703Z-debug.log
    pod@pod-PC2:~/src/temp$

# Additional information

    $ git describe
    v0.4.10-12-g75de9cb

**Comment by Poddster** [comment]
git checkout  af10b372773807
    npm install

And it seems to work ok here. Though `npm run dev` then fails.

**Comment by cooljeanius** [comment]
hm @rougetimelord do you think this is related to #363?

**Comment by rougetimelord** [comment]
We haven't been explicit about this, but we don't support node.js versions lower than v18. It seems like you are running Node 10.19.0

**Comment by cooljeanius** [comment]
> We haven't been explicit about this before, but we don't support node.js versions lower than v18. It seems like you are running Node 10.19.0

Hm, I wonder if there's a way to print a nicer error in that case, so people can understand why?

**Comment by rougetimelord** [comment]
> > We haven't been explicit about this before, but we don't support node.js versions lower than v18. It seems like you are running Node 10.19.0
> 
> Hm, I wonder if there's a way to print a nicer error in that case, so people can understand why?

We could add a install script, but honestly the NPM output is pretty clear and adding a script is complexity that we don't really need to get into
