### ISSUE TITLE
[feat] Add an undo button to the "Won't be blocked again" pop-up

### ISSUE THREAD

**Issue by Hamst3r** [kheina-com/Blue-Blocker#380]
Occasionally, more often than I'd like, when I manually block an account using the "1-click-blocker" extension, Blue Blocker will inform me that, "that account won't be blocked again", which isn't what I want. It wasn't clear that the account in question was blocked though, or was in the queue to be blocked eventually, it was just there on my screen, so I clicked the block button.

 Which leads a situation where Blue Blocker unblocks the account and says it won't be blocked again.
 
Is there something that could be done about this? My main idea is just to have an UNDO button on that pop-up window. There's an undo button on the pop-up when Blue Blocker blocks something, so there should be one on the pop-up when it unblocks/whitelists something too.

**Comment by rougetimelord** [comment]
Adding the bug tag because Blue Blocker shouldn't be picking up external block requests as an unblock

**Comment by rougetimelord** [comment]
Can't reproduce this behavior on Chrome with [1-click blocker](https://chromewebstore.google.com/detail/1-click-blocker-for-twitt/clhbjgbdocpldiobndgnlijdcmpppkhl), could you add information about what browser and extension you're using?

**Comment by Hamst3r** [comment]
I'm using this extension: https://chromewebstore.google.com/detail/1-click-blocker-for-twitt/clhbjgbdocpldiobndgnlijdcmpppkhl

I'm using it in Edge 131.0.2903.70

I've attached a video showing one way I can reproduce the problem.

https://github.com/user-attachments/assets/bcda6f07-8bf2-40ac-999d-ccc86d949946

Thanks for looking into this.

**Comment by rougetimelord** [comment]
That looks like you're using 1-click blocker to unblock the account and Blue Blocker is responding as expected?

**Comment by Hamst3r** [comment]
> That looks like you're using 1-click blocker to unblock the account and Blue Blocker is responding as expected?

That's a demonstration of the behavior, of the Blue Blocker pop-up appearing when 1-click blocker is used.

The problem is when it's an unintentional unblock, because it's not always clear that an account has already been blocked. There are situations where Twitter will show you the tweets from accounts you've blocked, or which have been blocked by Blue Blocker, because the accounts don't instantly disappear from your screen when Blue Blocker blocks them.

I'm asking for an UNDO button on that pop-up, to help with these unintentional unblocks, because my intention is not to unblock them, I simply can't tell that Blue Blocker had already gotten to it, or that I'm in a situation where Twitter is showing me the tweets of a blocked user (like in the Hidden Replies, which is a great place to find people to block).
