### ISSUE TITLE
[bug] Consent page sometimes will not deploy

### ISSUE THREAD

**Issue by Patcheresu** [kheina-com/Blue-Blocker#383]
**Describe the bug**
If you used an unloaded copy of Blue Blocker on Firefox, when the 0.4.13 update occurs, you will not be given the consent form, nor will it ever appear no matter how many times you reinstall the extension or restart the web browser.

Furthermore, until consent is acquired, the extension shall not function. No users are queued. No blocks are made. It's as if the extension is frozen.

**To Reproduce**
1. Acquire an unloaded copy of a version prior to 0.4.13.
2. Allow it to update naturally.
3. The consent form does not appear.
4. See error.

**Expected behavior**
The consent form should appear immediately after updating or installing allowing you to consent to data collection.

**Screenshots and console logs**
N/A

**Please fill in the following information:**
 - Browser Floorp, fork of Firefox that allowed me to load unloaded extensions because Firefox for some reason believes users should not be allowed to load loose extensions in Stable
 - Version 11.21.0 (64-bit)

**Additional context**
Workaround: Open the 'import' tab and note the url. 
moz-extension://XXXXXXXX/src/pages/safelist/index.html
Change it to: moz-extension://XXXXXXXX/src/pages/consent/index.html.
This will open the consent page, allowing you to consent to data collection and the extension will function normally afterwards.

I would also suggest checking if consent has been acquired and if it hasn't, opening the consent page every time the ~~user boots~~ web browser is started up until they accept or deny it, as well as having the consent form able to be accessed easily from the extension's settings or panel.

Thanks for the extension, I love it so much I dropped vanilla Firefox just to keep it! Happy you all were able to get it back in the hands of most users!

**Comment by rougetimelord** [comment]
I wanted to pop the consent page only when updates required it, which is why there's this list in `src/background/index.ts`:
https://github.com/kheina-com/Blue-Blocker/blob/4643ddf52a3d528496eb406f8247ba0e7330accd/src/background/index.ts#L128

I had not considered people using versions that are not 0.3.5, which was the latest version on AMO before 0.4.13. I'll get on it, thanks for reporting!

**Comment by rougetimelord** [comment]
Out of curiosity, could you check what `browser.runtime.getBrowserInfo` returns in Floorp?

**Comment by Patcheresu** [comment]
![image](https://github.com/user-attachments/assets/030b1910-ab6c-4aa1-adef-3ce575eac19a)
