### ISSUE TITLE
Support Manifest V2 for a little longer

### ISSUE THREAD

**Issue by konomikitten** [kheina-com/Blue-Blocker#39]
From https://extensionworkshop.com/documentation/publish/distribute-manifest-versions/:

> It is not possible to create a version of an extension that is MV2- and MV3-compatible. Therefore, you need a way of distributing both types of extension if you need to continue supporting older clients, such as Firefox ESR. (Firefox ESR 102.x, the extended support release for enterprises – large companies and organizations – is supported until September 2023, when the ESR release moves to a version supporting MV3).

Would it be possible for Blue Blocker to support MV2 until September? I know it's a bit of an ask but Debian Stable for example which is releasing soon will be stuck with MV2 until September at least.

**Comment by DanielleMiu** [comment]
well, shit.

at the very least you'll have v0.2.1 for the time being, but as far as I know, background scripts and the action api isn't available in manifest v2. I'll need to look into whether or not I can set up background scripts in v2 and/or parallel distribute v2 and v3 manifests for firefox

**Comment by DanielleMiu** [comment]
so it seems like it's fairly easy to revert the firefox manifest to v2. the checkmarks will be messed up again, but the service worker will still work fine, so not too bad. should be fixed in v0.2.3

**Comment by DanielleMiu** [comment]
holding off closing this until [`v0.2.3`](https://github.com/kheina-com/Blue-Blocker/pull/38) is deployed

**Comment by konomikitten** [comment]
Thanks for working on this.
