### ISSUE TITLE
Run in search results directly

### ISSUE THREAD

**Issue by sleepachu** [kheina-com/Blue-Blocker#49]
Being able to run this on search results directly would allow a user to deploy a 'worldcode' script such as '-filter:verified filter:blue_verified filter:replies' to block substantially all verified accounts. [This sounds like a good thing to empower]. The script used here https://gist.github.com/adalinesimonian/b52a753c9fd6c176598745df01ba12dc accomplishes this in a direct manner, but without this addon's flexibility; between the most recent popover method and the machinegun method used earlier this week, there's a strong synergy with this extension.

**Comment by DanielleMiu** [comment]
This is planned, and you make a really great point, it's just a pain in the ass adding a new request type to the addon.

eventually™
