### ISSUE TITLE
Feature request: block accounts that promote tweets

### ISSUE THREAD

**Issue by slifty** [kheina-com/Blue-Blocker#5]
It's nice to block blue users but also I have found it helpful to block any account that is advertising on twitter.  Would there be any interest in adding this?

**Comment by DanielleMiu** [comment]
you know, I'm hesitant to do this because there are already adblockers and extensions specifically for twitter that remove promoted tweets, and it feels out of scope for this extension.

**Comment by JamesBanana** [comment]
I support this feature request. People pay Twitter both for Blue and to promote tweets, so to me they are different sides off the same coin.

**Comment by jaredkotoff** [comment]
I don't want to just remove ads though. I want to block those accounts.

**Comment by DanielleMiu** [comment]
ok so having seen the new ceo, maybe I'll start looking into this

**Comment by fearthecowboy** [comment]
Indeed! This would be a fantastic feature.

Since Elmo  has made it clear that blocking an account affects it's ability to get crap show up in people's feeds via the algorithm, blocking accounts of promoted tweets can make it so they don't get algorithm'd up (theoretically)

Plus, have you noticed how all the ads these days are from super-sketchy gadget stores? eeew.

**Comment by alanpaone** [comment]
Advertisers _have_ to pay for a checkmark, or at least that was a policy that was supposed to be rolling out "soon" back in april, so blocking blue (and gold) checks ought to catch most of them

**Comment by jaredkotoff** [comment]
Probably a good idea to make gold a toggle switch like NFTs.
I feel like those are less bad. There are a lot more legitimate gold accounts that probably dont need to be blocked out right

**Comment by DanielleMiu** [comment]
already exists

**Comment by alanpaone** [comment]
I think there might be more than one type of gold checkmark, the current version is catching most of the crypto guys who are inexplicably paying for a gold check, but it seems to not catch brands. Cryptobros are definitely the more annoying of the two, but the brands promote more tweets. [This tweet](https://twitter.com/Twitter/status/1493027682795335680) is a good example, there's a bunch of both kinds in the replies, if you let the extension run for a bit, it'll block [@twitter](https://twitter.com/Twitter), but leave [@budweiserusa](https://twitter.com/budweiserusa) unscathed.

**Comment by jaredkotoff** [comment]
@DanielleMiu re: @alanpaone 
this is something else, the structure of the parsed item doesn't contain [`tweet`](https://github.com/kheina-com/Blue-Blocker/blob/d961ce6711ec6adc773fae78ea7eee1d6cdd06b2/parsers/instructions.js#L45)

```json
{
"tweet_results": {
   "result":{
      "__typename":"Tweet",
      "rest_id":"1642318156784979969",
      "core":{
         "user_results":{
            "result":{
               "__typename":"User",
               "id":"VXNlcjo4NzA2ODA5ODk=",
               "rest_id":"870680989",
               "affiliates_highlighted_label":{},
               "has_graduated_access":true,
               "is_blue_verified":false,
               "profile_image_shape":"Square",
               "legacy":{...},
               "professional":{...}
            }
         }
      },
      "edit_control":{...},
      "edit_perspective":{...},
      "is_translatable":false,
      "views":{...},
      "source":"<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>",
      "legacy":{...},
      "quick_promote_eligibility":{...}
   }
}
}
```

**Comment by jaredkotoff** [comment]
@alanpaone tracking here: https://github.com/kheina-com/Blue-Blocker/issues/115
