### ISSUE TITLE
Autoscroll

### ISSUE THREAD

**Issue by sleepachu** [kheina-com/Blue-Blocker#50]
Enabling an autoscroll would speed up loading names into the queue and prevent issues where threadloading stalls in cases where threads aren't being actively refreshed. I use a macro that jams the spacebar down because I'm both very dumb and very lazy, and it works for me. But I know a lot of people who are either dumber or lazier than me, and this would be helpful for them while also increasing automation by a large factor. 
Sequential scrolling by x /<200 pixels has a couple edge cases with frustrating outcomes - when ads obstruct certain ranges of the page, and near the bottom of a thread but before it loads new tweets: persistent scroll overcomes these cases consistently.

**Comment by DanielleMiu** [comment]
This seems a little out of scope for this addon. I get what you're trying to do, blocking _everyone_, but this is an addon that's meant to run in the background and juts clean things up while you're not looking, and not something that you run actively. plus, this would undoubtedly be hit by the rate limiting.

nothing's stopping you from running a different addon or making your own macro to do the scrolling, though

**Comment by tinoesroho** [comment]
would advise against running an autoscroll, personally, as it's much more likely to trigger a permanent suspension. ask me how i found that out. if you want to fuck aroundeth, @sleepachu, here's a bookmark. just point it at the twitter search prompt (h/t Adaline) -filter:verified filter:blue_verified and you are good to go.
```


javascript:const delay = o => new Promise(e => setTimeout(e, o));
var bigWait = 0;
var absoluteLimit = 300;
var currentCount = 0;
const doThingForever = async () => {
    if (absoluteLimit >= currentCount) {
        currentCount += 1;
        bigWait > 2 && (bigWait = 0, await delay(6e4)), window.scroll({
            top: 300,
            behavior: "smooth"
        }), await delay(2e3), window.scroll({
            top: -300,
            behavior: "smooth"
        }), bigWait += 1, setTimeout(doThingForever, 2e3);
    }
};
doThingForever();
```

**Comment by sleepachu** [comment]
i'm so sorry that happened to you! genuinely!
My use case is not so much nuke everything sequentially as it is specifically burning down certain accounts by thread. So I flip through my lil burn list a couple times a day and stack up a couple thousand names, so being super lazy and making a macro that jams down the spacebar for 30 seconds, lifts and repeats ten times does the job, and if other people aren't using it like that, there's no reason to add that function.
