### ISSUE TITLE
Add option to ignore accounts that restored their blue check by the "put blue check in profile comment" trick

### ISSUE THREAD

**Issue by cooljeanius** [kheina-com/Blue-Blocker#56]
Apparently if you put the words "blue check" in your profile comment, you can restore your legacy blue check without paying for Twitter Blue: https://twitter.com/kenklippenstein/status/1653084206631714816
I have seen several other accounts saying this as well. It might only be for accounts that previously had a legacy blue check, though? (I'm unable to test for myself to verify, though, since Twitter doesn't want to seem to save any edits I make to my profile lately...)

**Comment by DanielleMiu** [comment]
I'll keep an eye on this, I hadn't seen this before so I have no idea if its true or how true it is. if you can verify this at all though please let me know!

**Comment by sleepachu** [comment]
Suspect you are describing one or both of the following:
1. Something associated with an update to the 8 dollars plugin that recently restored functionality https://github.com/wseagar/eight-dollars/issues/108

2. Typing blue check 'restored' the blue check in the legacy verified user's personal view only, everyone else saw whatever their version of twitter let them see. I've seen a couple reports of it being patched yesterday, and I don't think it creates a new case (I believe the inside baseball here is that they can't really get rid of the legacy verified spreadsheet for Algoreasons and they may no longer have the ability/permissions to yank it.)
![2023-05-02 18_43_15-type blue check - Twitter Search _ Twitter — Mozilla Firefox](https://user-images.githubusercontent.com/108706279/235819422-078ceaf6-8dc8-4e16-9769-7fec55966f1f.png)

**Comment by cooljeanius** [comment]
> Suspect you are describing one or both of the following:
> 
>     1. Something associated with an update to the 8 dollars plugin that recently restored functionality [Fix issues with legacy verification list wseagar/eight-dollars#108](https://github.com/wseagar/eight-dollars/issues/108)

oh I actually stopped using eight-dollars after someone linked me to [twitter-real-verified](https://github.com/luiserdef/twitter-real-verified) in wseagar/eight-dollars#104, so now I use that instead
