### ISSUE TITLE
Problems signing in while extension is enabled

### ISSUE THREAD

**Issue by Swishilicous** [kheina-com/Blue-Blocker#57]
**Steps to reproduce**: 
1. Enable blue-blocker
2. Log out of twitter
3. Log in
4. Log in alert is sent to notifications but after the page reloads it asks you to login again

**Tested using**: Firefox extension

**Comment by Swishilicous** [comment]
It looks like I am stupid and this is fixed firefox just hasn't rolled out the update yet. Remember to check closed issues y'all.

**Comment by DanielleMiu** [comment]
this was also probably because Twitter was down today for like an hour or two lmao
