### ISSUE TITLE
simple feature req: add block queue length to logs

### ISSUE THREAD

**Issue by viomck** [kheina-com/Blue-Blocker#61]
would be nice to have the block queue size in this log:

```
[Blue Blocker] blocked [user](@[handle]) due to Twitter Blue verified.
```

if too inconvenient i can take a whack at it after work

**Comment by DanielleMiu** [comment]
this number is already available in the context menu (the menu that pops up when you click the extension icon in the toolbar). I'm also working on a queue visualizer ui element

**Comment by viomck** [comment]
oh that's what it is!  thank you!!
