### ISSUE TITLE
Providing a history/list of blocked accounts

### ISSUE THREAD

**Issue by NevanNedall** [kheina-com/Blue-Blocker#63]
It'd be nice to be able to see the accounts the extension has blocked in the event you did not see the pop-up for any given reason, to confirm it's working as intended.

**Comment by Down10** [comment]
Yes, a log of recent/all blocks to review would be helpful.

**Comment by Down10** [comment]
Also, I have been seeing accounts that I don't really care to block, but haven't chosen to follow, blip past me in a popup, so a way to go back and double check recent blocks would really be welcome. A way to see what account we have whitelisted would be good too, though that would be a separate request.

**Comment by alanpaone** [comment]
being able to export (or import!) a blocklist would be really cool, I've blocked a ton of accounts and it would be nice to be able to share the fruits of that labour with people who don't want to open every one of elon's tweets. I've also got a csv from the #BlocktheBlue account (RIP), which I've been 'importing' by opening each profile in a new tab with an extremely kludgy script. Incidentally, does the blocked users counter still count them if they're already blocked by the time it gets to them?

**Comment by DanielleMiu** [comment]
> being able to export (or import!) a blocklist would be really cool

agreed. an import/export of the safelist is on the docket, just whenever I get around to it. I burnt out a little bit, but I think the extension is in a pretty good spot right now so I've just been kinda chilling lately, but it shouldn't be much harder to add the same to the block history once that's implemented. still thinking about the best way to do that, though

> Incidentally, does the blocked users counter still count them if they're already blocked by the time it gets to them?

no, the addon only counts [successful replies](https://github.com/kheina-com/Blue-Blocker/blob/main/shared.js#L269) that the addon itself receives from the block endpoint. if you block a user, it's not counted, if addon finds someone that is [already blocked](https://github.com/kheina-com/Blue-Blocker/blob/main/shared.js#L303-L305), it will not be counted
