### ISSUE TITLE
Feature request: Follower-count threshold

### ISSUE THREAD

**Issue by sockpuppetclock** [kheina-com/Blue-Blocker#65]
Personally the only insufferable stuff I'd actually want to block comes from accounts with subatomic follower counts being pushed to the top of the replies. There's [this list](https://github.com/esqueer/twitter_blue_blocklist/) of Twitter Blue subscribers with <2000 followers but it's 4 months old which makes it largely useless to me.
Since there's already an optional check for accounts with >1M followers, could another optional check be added to only block accounts under a custom number of followers?

**Comment by DanielleMiu** [comment]
fixed by https://github.com/kheina-com/Blue-Blocker/pull/99
