### ISSUE TITLE
Additional Options for Blocked Popups

### ISSUE THREAD

**Issue by DanielleMiu** [kheina-com/Blue-Blocker#68]
> Notifications are annoying because they take up way to much space, but I've adapted to them. It'd be better if it had a size/placement option.

from https://addons.mozilla.org/en-US/firefox/addon/blue-blocker/reviews/1958673/

**Comment by DanielleMiu** [comment]
tentative for 0.2.5

**Comment by Klawz312** [comment]
Would it be possible to make the backgrounds of the notifications transparent so that they don't cover up parts of Twitter? The notifications font also has low contrast when Twitter is set to dark mode so it's hard to read the notification.

**Comment by DanielleMiu** [comment]
hey, could you take a screenshot of what the popups look like for you? the background should be `#1e1f25` and the text should be `#dddddd`, both of which are set by the extension's own [stylesheet](https://github.com/kheina-com/Blue-Blocker/blob/main/injected/toasts.css), twitter's theming shouldn't affect it. the contrast between these two is 12.10, not exactly high contrast by any means but shouldn't be low contrast either, so I'm wondering if you're experiencing a bug.

**Comment by DanielleMiu** [comment]
partially completed by https://github.com/kheina-com/Blue-Blocker/pull/99, but should probably include a location option and maybe other stuff. colors, etc. should probably be included under a separate advanced options menu or something
