### ISSUE TITLE
Purge queue

### ISSUE THREAD

**Issue by sleepachu** [kheina-com/Blue-Blocker#69]
Boundary case where queued accounts are suspended prior to blocking do not clear resulting in repeated bad requests and lockout. More probable issue if backlog is allowed to build over time or as more users are blocked (user will eventually add someone who is suspended inside the time between queueing and blocking).

**Comment by DanielleMiu** [comment]
good point

**Comment by april** [comment]
I'm getting constant errors because of this — an account that was suspended before it could be blocked. It would be great if it would back off an account if it failed to block it N times.

**Comment by DanielleMiu** [comment]
fixed by https://github.com/kheina-com/Blue-Blocker/pull/99
