### ISSUE TITLE
Add option to skip people retweeted (QRT?) by someone you follow

### ISSUE THREAD

**Issue by kheina** [kheina-com/Blue-Blocker#71]

**Comment by deonfoxfangs** [comment]
Not sure about etiquette for necro'ing old topics here but was coming to suggest this if there isn't already some way to do it within the add-on. The only thing bothersome I run into is that it blocks people that get retweeted into my timeline that are more or less harmless. If they're being retweeted/qrt'ed by someone I've chosen to follow I don't generally have a need to block them.

Thanks for your work!
