### ISSUE TITLE
Errors blocking when using tweetdeck.twitter.com

### ISSUE THREAD

**Issue by rjclark** [kheina-com/Blue-Blocker#72]
I noticed that, when browsing through https://tweetdeck.twitter.com, users are being queued properly, but the block call fails consistently and the users remain queued.

If I switch to https://twitter.com, then those queued users _are_ blocked correctly.

I do see errors in the console, but nothing in the error message indicates what exactly failed although I suspect it's a cross-domain problem.

```
[Blue Blocker] error: 
error { target: XMLHttpRequest, isTrusted: true, lengthComputable: false, loaded: 0, total: 0, srcElement: XMLHttpRequest, currentTarget: XMLHttpRequest, eventPhase: 2, bubbles: false, cancelable: false, … }
​  bubbles: false
  ​cancelBubble: false
  ​cancelable: false
  ​composed: false
  ​currentTarget: null
​  defaultPrevented: false
  ​eventPhase: 0
  ​explicitOriginalTarget: XMLHttpRequest { readyState: 4, timeout: 0, withCredentials: false, … }
  ​isTrusted: true
  ​lengthComputable: false
  ​loaded: 0
  ​originalTarget: XMLHttpRequest { readyState: 4, timeout: 0, withCredentials: false, … }
  ​returnValue: true
  ​srcElement: XMLHttpRequest { readyState: 4, timeout: 0, withCredentials: false, … }
  ​target: XMLHttpRequest { readyState: 4, timeout: 0, withCredentials: false, … }
  ​timeStamp: 0
  ​total: 0
  ​type: "error"
  ​<get isTrusted()>: function isTrusted()
  ​<prototype>: ProgressEventPrototype { lengthComputable: Getter, loaded: Getter, total: Getter, … }

[shared.js:178:11](moz-extension://978c7cc8-6d56-437c-9a99-3bb5693eac96/shared.js)
    BlockUser moz-extension://978c7cc8-6d56-437c-9a99-3bb5693eac96/shared.js:178
    (Async: EventListener.handleEvent)
    BlockUser moz-extension://978c7cc8-6d56-437c-9a99-3bb5693eac96/shared.js:177
    CheckBlockQueue moz-extension://978c7cc8-6d56-437c-9a99-3bb5693eac96/shared.js:142
    (Async: promise callback)
    CheckBlockQueue moz-extension://978c7cc8-6d56-437c-9a99-3bb5693eac96/shared.js:136
    (Async: setTimeout handler)
    sync moz-extension://978c7cc8-6d56-437c-9a99-3bb5693eac96/models/queue_consumer.js:55
    _timeout moz-extension://978c7cc8-6d56-437c-9a99-3bb5693eac96/models/queue_consumer.js:52
```

**Comment by DanielleMiu** [comment]
unfortunately I haven't really gotten around to adding tweetdeck support yet. cool that queuing works, though. for now I'd recommend opening a tab on twitter.com, then opening the tweetdeck tab. that way, the consumer is running on twitter and you queue from tweetdeck

**Comment by rjclark** [comment]
Sounds good, thank you. 

I had been closing everything and opening up twitter.com to process everything queued, but I'm glad that starting the consumer first will work. Appreciate the suggestion!

**Comment by DanielleMiu** [comment]
if you ever see the errors happening on tweetdeck you can just close the tab for 15-20 seconds and the consumer from twitter will notice the other stopped processing and pick up the queue again.

**Comment by DanielleMiu** [comment]
fixed by https://github.com/kheina-com/Blue-Blocker/pull/99

**Comment by rjclark** [comment]
Tested the new version and it does indeed correct the problem I was seeing. 

Thank you.
