### ISSUE TITLE
Request: Add option to block gold checkmarks. 

### ISSUE THREAD

**Issue by CountPatagium** [kheina-com/Blue-Blocker#73]
Says it all. Companies are getting around the blue block by being gold.

**Comment by DanielleMiu** [comment]
this already exists under the "affiliated" option. a reword is coming to be clearer

**Comment by CountPatagium** [comment]
I can find no evidence that it's working. I'm sitting on the page of a gold checkmarked account and hitting refresh. None of the "skip users..." boxes are checked.
