### ISSUE TITLE
pause collecting while still blocking queue

### ISSUE THREAD

**Issue by jonolds** [kheina-com/Blue-Blocker#75]
It would be great to have a button to pause collecting new usernames while still letting the queue run. Some blue checks are more annoying than others, and it would be nice to be able to fill up a queue in search and then go back to my timeline without adding unintentional blocks.

**Comment by Psotle** [comment]
I've raised a PR for this suggestion: https://github.com/kheina-com/Blue-Blocker/pull/76

**Comment by Down10** [comment]
Yes, this would be nice. My current method is to turn off the extension from the Manage Extensions panel, which is less than ideal.

**Comment by DanielleMiu** [comment]
https://github.com/kheina-com/Blue-Blocker/pull/76
