### ISSUE TITLE
BlueBlocker fails to block after logout and log back in

### ISSUE THREAD

**Issue by viomck** [kheina-com/Blue-Blocker#77]
<img width="615" alt="image" src="https://user-images.githubusercontent.com/26819786/236635248-87ea5926-e6c9-436f-994a-8b70276af72b.png">

I get this error when BlueBlocker tries to run a queued block that was queued before my current login session. This might be because `headers` is pre-calculated and stored in the queue, which means when the CSRF token changes the queued blocks are all broken.  Not sure if this is the case though.

**Comment by DanielleMiu** [comment]
hey, what version of the extension do you have? a fix was pushed for this a few versions ago and the csrf token should be pulled directly from the cookie before the request is made

**Comment by viomck** [comment]
v0.2.4 firefox

**Comment by viomck** [comment]
though perhaps it updated between then and now, since i'm no longer experiencing the issue.  thx!
