### ISSUE TITLE
skip users followed by users I follow

### ISSUE THREAD

**Issue by roland-detterbeck** [kheina-com/Blue-Blocker#79]
This could be a good option to prevent overblocking:
"skip users followed by users I follow"

If possible also add an option to define the number of followers:
"skip users followed by [n] users I follow"

**Comment by DanielleMiu** [comment]
this would require checking the response object and see if that information is available, but this may not be possible with how the extension works

**Comment by rougetimelord** [comment]
Duped by #122, closing this issue to keep track of this there
