### ISSUE TITLE
Twitter returning legacy checkmark and labelling it as Twitter Blue 

### ISSUE THREAD

**Issue by rizkisrq** [kheina-com/Blue-Blocker#8]
Twitter is returning legacy checkmarks on certain users (threshold unknown) and purposely labelled it as Twitter Blue. 

An article relevant to this issue can be found here as many celebrities are trying to remove their checkmarks: https://www.avclub.com/celebrities-now-working-to-remove-their-apparently-mand-1850366148 

However, using filter:verified and filter:verified_blue still works to differentiate legacy checkmarks and Twitter Blue checkmarks. Evidence:  Maybe this can be used to differentiate legacy and blue checkmarks. 

**Example of filter:verified_blue**
![example of filter:verified_blue](https://user-images.githubusercontent.com/8591882/233813464-7619df31-816c-4950-9b69-88b9b5f38b2d.png)

**Example of filter:verified**
![example of filter:verfieid](https://user-images.githubusercontent.com/8591882/233813469-0e6c2f44-da61-4f7d-a564-623a56cf414e.png)

**Comment by Suyooo** [comment]
Pull request regarding this change: #10 

It seems there is no way to distinguish between these two types of "Verified" in the API used for the add-on, so for now, it's just checking for a follower count above 1 million, since that seems to be the cutoff. Not sure much more can be done there.

**Comment by namazso** [comment]
Wasn't there a full scrape of legacy verified accounts? Could just include it as a whitelist and avoid blocking people there

**Comment by rizkisrq** [comment]
> Wasn't there a full scrape of legacy verified accounts? Could just include it as a whitelist and avoid blocking people there
> 
> edit: https://gist.github.com/travisbrown/b50d6745298cccd6b1f4697e4ec22103

Yea this one could work as temporary whitelist as the situation has changed once again. Some users who were given their checkmark back now reported that Twitter has made them subscribe to the actual Twitter Blue without their consent. 

Examples:
- Matt Binder: https://twitter.com/mattbinder/status/1650237562223579136?s=46
- Hoe Zaay: https://twitter.com/hoezaay/status/1650254350412058624?s=46
- Drill: https://twitter.com/dril/status/1650234240922157056?s=46
