### ISSUE TITLE
Poor Perforance with Large Queue

### ISSUE THREAD

**Issue by kheina** [kheina-com/Blue-Blocker#82]
from a chrome webstore review
> 2) Likely due to the size of the backlog, I started noticing really bad browser performance. It seems like the browser would freeze up for a moment every few seconds, even if the block interval was increased.

**Comment by DanielleMiu** [comment]
potentially fixed by https://github.com/kheina-com/Blue-Blocker/pull/99

**Comment by rougetimelord** [comment]
Hopefully fixed by the 0.4.0 release too!
