### ISSUE TITLE
Feature request: "whitelist" from the queue list

### ISSUE THREAD

**Issue by NamesMark** [kheina-com/Blue-Blocker#85]
I'm getting too many "false positives" - people who I wouldn't want to block, but don't follow myself (and that don't match either of filters). #78 proposes to "edit and view queue" with options to delete accounts from the queue (#69 is also related). I propose an option to whitelist accounts, which saves them to a permanent list, removes them from the queue and prevents them from getting there again. 

My suggested workflow: collect accounts, review the list, whitelist "good accounts", resume blocking (it would require an option to pause blocking while still collecting)

**Comment by DanielleMiu** [comment]
relatedish: https://github.com/kheina-com/Blue-Blocker/pull/76
this is planned. more granular control over the queue is planned but idk when.
ie: pause blocking, pause queuing, view and edit queue, view x previous blocks

for now, you can review blocked users via the popups. undoing a block from the popup adds them to a whitelist

**Comment by DanielleMiu** [comment]
fixed by https://github.com/kheina-com/Blue-Blocker/pull/99
