### ISSUE TITLE
Switching accounts?

### ISSUE THREAD

**Issue by jaredkotoff** [kheina-com/Blue-Blocker#87]
What happens, or how does this handle, when you switch between multiple accounts?

**Comment by DanielleMiu** [comment]
this would be an edge cat that most users probably won't encounter, and depends on how twitter's auth works. auth credentials are taken from the request and stored with the user in the queue. so as long as twitter doesn't invalidate those credentials (which they would, if they were smart) when you log out, theoretically it would still work. but that's just a guess

**Comment by jaredkotoff** [comment]
> edge cat
😄 
But to clarify, I'm not talking about logging out. I'm referring to switching accounts via the user menu.
If the blocks are queued with user info attached to them, then it might just work as expected!

**Comment by DanielleMiu** [comment]
ah, I'm not too suuure. I would thiiink it would work the same way ? that would be the easiest thing to implement, just store multiple auth tokens in local storage. but I would need to check

**Comment by DanielleMiu** [comment]
thinking about this more, it probably still doesn't answer this question, annoyingly. would still require some investigation into how twitter's tokens work

**Comment by jaredkotoff** [comment]
I need to look into more too, but i think the token stays the same. Probably need to make an array of Queues and try to detect when switching accounts and switch Queues to match

**Comment by DanielleMiu** [comment]
closed in favor of #180
