### ISSUE TITLE
gif blocker

### ISSUE THREAD

**Issue by crispybegs** [kheina-com/Blue-Blocker#91]
i know it's outside your wheelhouse, but just fyi i'd pay good money for an extension that blocks anyone who uses this gif

<img width="399" alt="Screenshot 2023-05-12 at 10 06 13" src="https://github.com/kheina-com/Blue-Blocker/assets/129169122/7108ff32-3c75-49da-a7b1-255093f79202">

**Comment by DanielleMiu** [comment]
yeah sorry not doing this lol though I wouldn't hate something like this existing either
