### ISSUE TITLE
does not block nearly any accounts when scrolling a heavily blue checked feed

### ISSUE THREAD

**Issue by gitsreadymeal** [kheina-com/Blue-Blocker#93]
only blocks maybe a few percent of blue check accounts. the notifications of the blocks are also very large on the screen and don't go away, the page must be refreshed. when clicking on a feed with hundreds of blue check replies, only a handful get blocked no matter how long you stay on the feed or scroll through it

**Comment by DanielleMiu** [comment]
hi, that's very weird, I'm not aware of any issues with blocking at the moment. could you let me know what the version of your installed extension is also also check the size of the queue? users are blocked in the background so that twitter doesn't rate limit your account

**Comment by gitsreadymeal** [comment]
thank you, i don't know what rate limit is could you explain? it's version 0.2.5 btw and i don't know how to check the size of the queue.

**Comment by gitsreadymeal** [comment]
on pc app btw

**Comment by DanielleMiu** [comment]
rate limiting is when you try to perform too many actions on a website that the server needs to handle and the server will stop you from performing any more, usually by logging you out.

you can check the queue, and all extension options, by clicking the extension icon (the Blue B with the X in it) from the toolbar. if it's not on your toolbar, it may be in your extension list, which you can find by clicking the little puzzle piece in your toolbar and finding the icon.

**Comment by gitsreadymeal** [comment]
thanks, in the cue, even with block interval set to 5 seconds, i am still seeing unblocked accounts on the feed and it is still slow going. so far only 135 accounts blocked with 85 cued

**Comment by gitsreadymeal** [comment]
on a political feed rn and all the top replies are blue check bots none are blocked

**Comment by gitsreadymeal** [comment]
i think i understand, when scrolling a feed, you can still see the blue checks because they are queued for blocking, but they will eventually be blocked is that correct?

**Comment by DanielleMiu** [comment]
yes that's correct. this extension doesn't actually modify the page itself at all. instead it relies on twitter's own blocking api to block them from your account. while they are queued you will still see them. even after they are blocked, you'll still be able to see them on the page until you navigate away and the sever needs to fetch new tweets for you

**Comment by gitsreadymeal** [comment]
thanks again. some blue check accounts that i don't follow but are on my timeline get blocked, but there is no way to find them in my block list to unblock them or see most recently blocked. how do i find those most recently blocked accounts if in case i need to unblock?

**Comment by DanielleMiu** [comment]
currently only through the popups. eventually, there will be a page to view the last X blocked accounts and unblock them. additionally the menu gives you options to skip accounts you follow and other settings

**Comment by gitsreadymeal** [comment]
nice
