### ISSUE TITLE
Feature request: Block all accounts that like a certain tweet

### ISSUE THREAD

**Issue by gitsreadymeal** [kheina-com/Blue-Blocker#94]
This will apply to any and every account no matter the designation(check or no check, with an option to block either or both). 

EG: Hateful and/or disingenuous tweet gets 500+ likes for example. Click a prompt to block all accounts that liked it.

**Comment by sleepachu** [comment]
hyg https://megablock.xyz/

**Comment by gitsreadymeal** [comment]
> hyg https://megablock.xyz/

thanks, i can't get past this screen though

<img width="520" alt="Untitled" src="https://github.com/kheina-com/Blue-Blocker/assets/133597467/d2eaf5fe-17b9-4061-b248-fd94227398f8">

**Comment by sonololo** [comment]
I recommend going with https://dmstern.github.io/likers-blocker/ ; it works well for me. The only caveat with it that you should pay attention to `IMPORTANT` section there, if you won't, then it will not work.

I don't think that Blues-Blocker addon needs to compete with other addons that do separate stuff.

**Comment by gitsreadymeal** [comment]
Thank you that is a great addition to blue blocker, however, I clicked on a tweet with over 5000 likes and it only blocked 115 of them. Do I need to change the settings?

**Comment by gitsreadymeal** [comment]
Ok I adjusted the scrolling speed and it made it to over 1000 blocks it could be my internet connection or because I was suddenly logged out by twitter. Thanks again
