### ISSUE TITLE
Feature request: lower the 1M+ follower skip to just below 1M

### ISSUE THREAD

**Issue by Bellzine** [kheina-com/Blue-Blocker#95]
I'm not sure exactly how it works at the moment but I'm concerned that if somebody who hovers around 990k or whatever goes above 1M and is "verified" and then dips back down to 999,999 but keeps the verification, that'll bypass the skip and they'll be blocked. Kind of niche but I do think it's worth setting the skip to five or ten thousand below a million if it's not already to counteract follower bot clear outs dropping people's totals. Thank you for the wonderful add-on btw, love no longer having to see the trash of the internet at the top of the replies every time.

**Comment by DanielleMiu** [comment]
included under https://github.com/kheina-com/Blue-Blocker/issues/65
