### ISSUE TITLE
Unblock non-Blue subscribers from blocklist

### ISSUE THREAD

**Issue by SWinxy** [kheina-com/Blue-Blocker#96]
I would like to give amnesty to those who don't have Blue anymore using an option to unblock people on my blocked list who wouldn't be blocked by the current settings.

**Comment by Psotle** [comment]
That'd be fiddly to keep track of: and risks unblocking people you manually blocked for other reasons.

**Comment by SWinxy** [comment]
I'd imagine that I'm the only one who has exclusively Blue subscribers on my block list.

**Comment by DanielleMiu** [comment]
unfortunately, I don't think this is possible the way you're envisioning it.
