### ISSUE TITLE
Feature Request: Minimize Block Notifications

### ISSUE THREAD

**Issue by ariskoumis** [kheina-com/Blue-Blocker#97]
With a low block interval, the block notifications can add up. This results in the notifications cluttering up the left side of the page; for example:
<img width="794" alt="image" src="https://github.com/kheina-com/Blue-Blocker/assets/14084061/9569b2ed-b265-4927-bed7-7869f7a83633">

Some suggestions to address this.
- Make the time each notification is visible scale with the user-selected block interval.
- Add a "dismiss" button to each notification, so the user can quickly X them off the page.
- Stack the block notifications. One notification that says "blocked N Blue users that replied to this tweet". Maybe with a "see who" option that lists those users.

**Comment by DanielleMiu** [comment]
probably not going to do this, actually. instead allowing you to set how long the popup stays on screen

**Comment by DanielleMiu** [comment]
used the wrong fucking button
